// prettier-ignore
export const FACILITIES =[
  {id:"drplFacility_item_1", value:"KO43", text:"Abrahamsberg BP"},
  {id:"drplFacility_item_2", value:"GO41", text:"Abrahamsbergssk. (idrott)"},
  {id:"drplFacility_item_3", value:"SO41", text:"Abrahamsbergssk. (möte)"},
  {id:"drplFacility_item_4", value:"GA01", text:"Adolf Fredriks Musikskola"},
  {id:"drplFacility_item_5", value:"GO02", text:"Adolfsbergsskolan"},
  {id:"drplFacility_item_6", value:"GR03", text:"Akalla Grundskola"},
  {id:"drplFacility_item_7", value:"KR01", text:"Akalla Gårds BP"},
  {id:"drplFacility_item_8", value:"GO01", text:"Alviksskolan"},
  {id:"drplFacility_item_9", value:"KN01", text:"Aspuddens IP"},
  {id:"drplFacility_item_10", value:"GN01", text:"Aspuddens Skola"},
  {id:"drplFacility_item_11", value:"KN21", text:"Axelsbergs BP"},
  {id:"drplFacility_item_12", value:"GP33", text:"Backluraskolan"},
  {id:"drplFacility_item_13", value:"KG21", text:"Bagarmossens BP"},
  {id:"drplFacility_item_14", value:"GG21", text:"Bagarmossens Skola"},
  {id:"drplFacility_item_15", value:"KK02", text:"Bandhagens Gymnasium BP"},
  {id:"drplFacility_item_16", value:"GK02", text:"Bandhagens Skola"},
  {id:"drplFacility_item_17", value:"KK03", text:"Bandhagens Skola BP"},
  {id:"drplFacility_item_18", value:"IK01", text:"Bandhagshallen"},
  {id:"drplFacility_item_19", value:"IO82", text:"Beckombergahallen"},
  {id:"drplFacility_item_20", value:"KA15", text:"Bellevue BP"},
  {id:"drplFacility_item_21", value:"KG22", text:"Bergholms BP"},
  {id:"drplFacility_item_22", value:"GG01", text:"Björkhagens Skola (idrott"},
  {id:"drplFacility_item_23", value:"SG01", text:"Björkhagens skola (möte)"},
  {id:"drplFacility_item_24", value:"GP72", text:"Björnbodaskolan"},
  {id:"drplFacility_item_25", value:"KO82", text:"Blackebergs BP"},
  {id:"drplFacility_item_26", value:"IO81", text:"Blackebergshallen"},
  {id:"drplFacility_item_27", value:"GO83", text:"Blackebergsskolan"},
  {id:"drplFacility_item_28", value:"BBLEK", text:"Blekholmsterrassen"},
  {id:"drplFacility_item_29", value:"KM01", text:"Bredängs BP"},
  {id:"drplFacility_item_30", value:"IM03", text:"Bredängsbadet"},
  {id:"drplFacility_item_31", value:"IM02", text:"Bredängshallen"},
  {id:"drplFacility_item_32", value:"GO11", text:"Bromma Gymnasium"},
  {id:"drplFacility_item_33", value:"KO52", text:"Bromma Sportfält"},
  {id:"drplFacility_item_34", value:"KQ51", text:"Bromstens IP"},
  {id:"drplFacility_item_35", value:"GQ51", text:"Bromstensskolan"},
  {id:"drplFacility_item_36", value:"KG23", text:"Brotorps BP"},
  {id:"drplFacility_item_37", value:"KN52", text:"Brännkyrka BP"},
  {id:"drplFacility_item_38", value:"IN51", text:"Brännkyrkahallen"},
  {id:"drplFacility_item_39", value:"KK04", text:"Bäckahagens BP"},
  {id:"drplFacility_item_40", value:"GK21", text:"Bäckahagens Skola"},
  {id:"drplFacility_item_41", value:"KK32", text:"Bäverdalens BP"},
  {id:"drplFacility_item_42", value:"KR13", text:"Dalhagens BP"},
  {id:"drplFacility_item_43", value:"GA83", text:"Eiraskolan"},
  {id:"drplFacility_item_44", value:"GN12", text:"Ekensbergsskolan"},
  {id:"drplFacility_item_45", value:"KA16", text:"Ekhagens BP"},
  {id:"drplFacility_item_46", value:"KQ45", text:"Elinsborgs BP"},
  {id:"drplFacility_item_47", value:"IA12", text:"Engelbrektshallen"},
  {id:"drplFacility_item_48", value:"KF32", text:"Enskede IP"},
  {id:"drplFacility_item_49", value:"GF31", text:"Enskede Skola (idrott)"},
  {id:"drplFacility_item_50", value:"GF21", text:"Enskedefältets Skola"},
  {id:"drplFacility_item_51", value:"IF12", text:"Enskedehallen"},
  {id:"drplFacility_item_52", value:"KD47", text:"Eriksdals BP"},
  {id:"drplFacility_item_53", value:"ID40", text:"Eriksdalsbadet"},
  {id:"drplFacility_item_54", value:"ID42", text:"Eriksdalshallen"},
  {id:"drplFacility_item_55", value:"SD41", text:"Eriksdalsskolan"},
  {id:"drplFacility_item_56", value:"GD41", text:"Eriksdalsskolan (idrott)"},
  {id:"drplFacility_item_57", value:"GA91", text:"Essinge Skola"},
  {id:"drplFacility_item_58", value:"GI01", text:"Fagersjöskolan"},
  {id:"drplFacility_item_59", value:"KI14", text:"Farsta IP"},
  {id:"drplFacility_item_60", value:"II14", text:"Farstahallarna, Farsta IP"},
  {id:"drplFacility_item_61", value:"II15", text:"Farstahallen"},
  {id:"drplFacility_item_62", value:"ID44", text:"Forsgrenska"},
  {id:"drplFacility_item_63", value:"ID43", text:"Forsgrenskabadet"},
  {id:"drplFacility_item_64", value:"KL01", text:"Fruängens BP"},
  {id:"drplFacility_item_65", value:"GL01", text:"Fruängens Skola (idrott)"},
  {id:"drplFacility_item_66", value:"IA11", text:"GIH-badet"},
  {id:"drplFacility_item_67", value:"GD05", text:"Globala gymnasiet"},
  {id:"drplFacility_item_68", value:"KQ20", text:"Gläntans IP"},
  {id:"drplFacility_item_69", value:"KR03", text:"Granby BP"},
  {id:"drplFacility_item_70", value:"KP02", text:"Grimsta BP"},
  {id:"drplFacility_item_71", value:"KP01", text:"Grimsta IP"},
  {id:"drplFacility_item_72", value:"IP01", text:"Grimstahallen"},
  {id:"drplFacility_item_73", value:"KN11", text:"Gröndals BP"},
  {id:"drplFacility_item_74", value:"KH04", text:"Gubbängens BP"},
  {id:"drplFacility_item_75", value:"KH01", text:"Gubbängens IP"},
  {id:"drplFacility_item_76", value:"KH02", text:"Gubbängens Sportfält"},
  {id:"drplFacility_item_77", value:"GH01", text:"Gubbängsbadet"},
  {id:"drplFacility_item_78", value:"KH03", text:"Gubbängsfältet Rugby"},
  {id:"drplFacility_item_79", value:"IH02", text:"Gubbängshallen"},
  {id:"drplFacility_item_80", value:"GH02", text:"Gubbängsskolan (idrott)"},
  {id:"drplFacility_item_81", value:"GQ44", text:"Gullingeskolan"},
  {id:"drplFacility_item_82", value:"GA21", text:"Gustav Vasa Skola (idrott"},
  {id:"drplFacility_item_83", value:"IA31", text:"Gärdeshallen"},
  {id:"drplFacility_item_84", value:"SA71", text:"Gärdesskolan (klassrum)"},
  {id:"drplFacility_item_85", value:"KA31", text:"Gärdesskolans bollplan"},
  {id:"drplFacility_item_86", value:"KA71", text:"Gärdets Sportfält"},
  {id:"drplFacility_item_87", value:"KK12", text:"Hagsätra IP"},
  {id:"drplFacility_item_88", value:"IK25", text:"Hagsätrahallen"},
  {id:"drplFacility_item_89", value:"KD50", text:"Hammarby IP"},
  {id:"drplFacility_item_90", value:"GG03", text:"Hammarby Skola Norra"},
  {id:"drplFacility_item_91", value:"KG01", text:"Hammarbyhöjden IP"},
  {id:"drplFacility_item_92", value:"GG02", text:"Hammarbyskolan Södra"},
  {id:"drplFacility_item_93", value:"KL11", text:"Herrängens BP"},
  {id:"drplFacility_item_94", value:"GL11", text:"Herrängens Skola"},
  {id:"drplFacility_item_95", value:"KA13", text:"Hjorthagens IP"},
  {id:"drplFacility_item_96", value:"IA13", text:"Hjorthagshallen"},
  {id:"drplFacility_item_97", value:"KQ44", text:"Hjulsta BP"},
  {id:"drplFacility_item_98", value:"GQ47", text:"Hjulstaskolan (idrott)"},
  {id:"drplFacility_item_99", value:"KR12", text:"Husby BP"},
  {id:"drplFacility_item_100", value:"KR11", text:"Husby Ishall"},
  {id:"drplFacility_item_101", value:"IR10", text:"Husbybadet"},
  {id:"drplFacility_item_102", value:"SS13", text:"Husbybadet skolsim"},
  {id:"drplFacility_item_103", value:"GR13", text:"Husbygårdsskolan"},
  {id:"drplFacility_item_104", value:"IR11", text:"Husbyhallen"},
  {id:"drplFacility_item_105", value:"GN32", text:"Hägerstenshamnens Skola"},
  {id:"drplFacility_item_106", value:"KN33", text:"Hägerstensåsens BP"},
  {id:"drplFacility_item_107", value:"GN31", text:"Hägerstensåsens Skola"},
  {id:"drplFacility_item_108", value:"KP11", text:"Hässelby Gårds BP"},
  {id:"drplFacility_item_109", value:"KP10", text:"Hässelby IP"},
  {id:"drplFacility_item_110", value:"KP31", text:"Hässelby Villastads BP"},
  {id:"drplFacility_item_111", value:"GP11", text:"Hässelbygårdssk. (idrott)"},
  {id:"drplFacility_item_112", value:"SP11", text:"Hässelbygårdsskolan"},
  {id:"drplFacility_item_113", value:"IP31", text:"Hässelbyhallen"},
  {id:"drplFacility_item_114", value:"KP24", text:"Hässelängens BP"},
  {id:"drplFacility_item_115", value:"KI11", text:"Hästhagens BP"},
  {id:"drplFacility_item_116", value:"GI13", text:"Hästhagsskolan"},
  {id:"drplFacility_item_117", value:"GD01", text:"Högalidsskolan (idrott)"},
  {id:"drplFacility_item_118", value:"KK23", text:"Högdalens BP"},
  {id:"drplFacility_item_119", value:"IK21", text:"Högdalsbadet"},
  {id:"drplFacility_item_120", value:"IK22", text:"Högdalshallen"},
  {id:"drplFacility_item_121", value:"SO23", text:"Höglandsskolan"},
  {id:"drplFacility_item_122", value:"KH12", text:"Hökarängens BP"},
  {id:"drplFacility_item_123", value:"KH14", text:"Hökarängens BP"},
  {id:"drplFacility_item_124", value:"GH11", text:"Hökarängsskolan (idrott)"},
  {id:"drplFacility_item_125", value:"GL31", text:"Johan Skyttesk. (idrott)"},
  {id:"drplFacility_item_126", value:"SL31", text:"Johan Skyttesk. (möte)"},
  {id:"drplFacility_item_127", value:"KA22", text:"Johannes BP"},
  {id:"drplFacility_item_128", value:"GA41", text:"Johannes Skola"},
  {id:"drplFacility_item_129", value:"KM31", text:"Johannesdal BP"},
  {id:"drplFacility_item_130", value:"ID50", text:"Kanalhallen"},
  {id:"drplFacility_item_131", value:"GA24", text:"Karlbergs skola"},
  {id:"drplFacility_item_132", value:"GD42", text:"Katarina Norra Skola"},
  {id:"drplFacility_item_133", value:"KD43", text:"Katarina Södra BP"},
  {id:"drplFacility_item_134", value:"GD43", text:"Katarina Södra Skola"},
  {id:"drplFacility_item_135", value:"GA81", text:"Klastorpsskolan"},
  {id:"drplFacility_item_136", value:"KQ61", text:"Knutby BP"},
  {id:"drplFacility_item_137", value:"GQ30", text:"Knutbyskolan"},
  {id:"drplFacility_item_138", value:"IA82", text:"Konradsbergshallen"},
  {id:"drplFacility_item_139", value:"KA83", text:"Kristinebergs IP"},
  {id:"drplFacility_item_140", value:"GA92", text:"Kristinebergsskolan"},
  {id:"drplFacility_item_141", value:"IA61", text:"Kronobergsbadet"},
  {id:"drplFacility_item_142", value:"GA87", text:"Kungsholmens Grund Nya"},
  {id:"drplFacility_item_143", value:"GA88", text:"Kungsholmens Grundskola"},
  {id:"drplFacility_item_144", value:"GA82", text:"Kungsholmens Gym. (idrott"},
  {id:"drplFacility_item_145", value:"SA82", text:"Kungsholmens Gym. (möte)"},
  {id:"drplFacility_item_146", value:"KA81", text:"Kungsholmens Gymnasium BP"},
  {id:"drplFacility_item_147", value:"KR23", text:"Kvarnbacka BP"},
  {id:"drplFacility_item_148", value:"GR22", text:"Kvarnbackaskolan"},
  {id:"drplFacility_item_149", value:"GQ63", text:"Kvarnbyskolan"},
  {id:"drplFacility_item_150", value:"KI12", text:"Kvickentorps BP"},
  {id:"drplFacility_item_151", value:"KP41", text:"Kälvesta BP"},
  {id:"drplFacility_item_152", value:"KL33", text:"Kämpetorps BP"},
  {id:"drplFacility_item_153", value:"IL33", text:"Kämpetorpshallen"},
  {id:"drplFacility_item_154", value:"KG11", text:"Kärrtorps IP"},
  {id:"drplFacility_item_155", value:"IG11", text:"Kärrtorpshallen"},
  {id:"drplFacility_item_156", value:"IN42", text:"Liljeholmshallen"},
  {id:"drplFacility_item_157", value:"GA02", text:"Lilla Adolf Fredrik Skola"},
  {id:"drplFacility_item_158", value:"GF20", text:"Lindeskolan"},
  {id:"drplFacility_item_159", value:"KL21", text:"Lisebergs BP"},
  {id:"drplFacility_item_160", value:"GP12", text:"Loviselundsskolan"},
  {id:"drplFacility_item_161", value:"KL34", text:"Långbro BP"},
  {id:"drplFacility_item_162", value:"GL32", text:"Långbrodals Gamla Skola"},
  {id:"drplFacility_item_163", value:"KD01", text:"Långholmens BP"},
  {id:"drplFacility_item_164", value:"GI21", text:"Magelungsskolan"},
  {id:"drplFacility_item_165", value:"KP23", text:"Maltesholmsskolans BP"},
  {id:"drplFacility_item_166", value:"GD02", text:"Maria Skola"},
  {id:"drplFacility_item_167", value:"GA61", text:"Matteusskolan (idrott)"},
  {id:"drplFacility_item_168", value:"SA61", text:"Matteusskolan (möte)"},
  {id:"drplFacility_item_169", value:"KQ25", text:"Mellangårdens BP"},
  {id:"drplFacility_item_170", value:"IL02", text:"Mälarhöjden Gymnastikhall"},
  {id:"drplFacility_item_171", value:"KL02", text:"Mälarhöjdens IP"},
  {id:"drplFacility_item_172", value:"GN61", text:"Mälarhöjdens Skola (idr)"},
  {id:"drplFacility_item_173", value:"KO31", text:"Nockebyhovs BP"},
  {id:"drplFacility_item_174", value:"KA43", text:"Norra Reals Bollplan"},
  {id:"drplFacility_item_175", value:"GA43", text:"Norra Reals Gymn (idrott)"},
  {id:"drplFacility_item_176", value:"SA43", text:"Norra Reals Gymn (möte)"},
  {id:"drplFacility_item_177", value:"GO61", text:"Norra Ängby Skola"},
  {id:"drplFacility_item_178", value:"KO44", text:"Nya Element BP"},
  {id:"drplFacility_item_179", value:"GN41", text:"Nybohovsskolan"},
  {id:"drplFacility_item_180", value:"KG03", text:"Nytorps BP"},
  {id:"drplFacility_item_181", value:"KP51", text:"Nälsta BP"},
  {id:"drplFacility_item_182", value:"IP52", text:"Nälstabadet"},
  {id:"drplFacility_item_183", value:"GP51", text:"Nälstaskolan"},
  {id:"drplFacility_item_184", value:"KO32", text:"Olovslunds BP"},
  {id:"drplFacility_item_185", value:"GO32", text:"Olovslundsskolan"},
  {id:"drplFacility_item_186", value:"KK13", text:"Ormkärrs BP"},
  {id:"drplFacility_item_187", value:"GK12", text:"Ormkärrsskolan (idrott)"},
  {id:"drplFacility_item_188", value:"IP32", text:"Riddersvikshallen"},
  {id:"drplFacility_item_189", value:"KQ62", text:"Rinkeby BP"},
  {id:"drplFacility_item_190", value:"IQ62", text:"Rinkebyhallen"},
  {id:"drplFacility_item_191", value:"SQ61", text:"Rinkebyskolan"},
  {id:"drplFacility_item_192", value:"KK31", text:"Rågsveds BP"},
  {id:"drplFacility_item_193", value:"GK31", text:"Rågsvedsskolan"},
  {id:"drplFacility_item_194", value:"GA84", text:"Rålambshovsskolan"},
  {id:"drplFacility_item_195", value:"IA22", text:"Rödabergshallen"},
  {id:"drplFacility_item_196", value:"IA41", text:"S:t Erikshallen"},
  {id:"drplFacility_item_197", value:"KH21", text:"Sandåkra BP"},
  {id:"drplFacility_item_198", value:"GH22", text:"Sandåkraskolan"},
  {id:"drplFacility_item_199", value:"IE51", text:"Sjöstadshallen"},
  {id:"drplFacility_item_200", value:"GE51", text:"Sjöstadsskolan"},
  {id:"drplFacility_item_201", value:"IF01", text:"Sjöviksskolan"},
  {id:"drplFacility_item_202", value:"KL81", text:"Sjöängens BP"},
  {id:"drplFacility_item_203", value:"GL81", text:"Sjöängsskolan"},
  {id:"drplFacility_item_204", value:"IF14", text:"Skanskvarnshallen"},
  {id:"drplFacility_item_205", value:"GF12", text:"Skanskvarnsskolan (idrott"},
  {id:"drplFacility_item_206", value:"ID51", text:"Skanstullshallen"},
  {id:"drplFacility_item_207", value:"GG31", text:"Skarpatorpsskolan F-3"},
  {id:"drplFacility_item_208", value:"KG12", text:"Skarpnäcks BP"},
  {id:"drplFacility_item_209", value:"GG12", text:"Skarpnäcks Skola"},
  {id:"drplFacility_item_210", value:"KG32", text:"Skarpnäcks Sportfält"},
  {id:"drplFacility_item_211", value:"IG32", text:"Skarpnäckshallen"},
  {id:"drplFacility_item_212", value:"SM12", text:"Skärholmens gymnasium"},
  {id:"drplFacility_item_213", value:"IM11", text:"Skärholmsbadet"},
  {id:"drplFacility_item_214", value:"IM12", text:"Skärholmshallen"},
  {id:"drplFacility_item_215", value:"KH22", text:"Sköndals BP"},
  {id:"drplFacility_item_216", value:"IH21", text:"Sköndalshallen"},
  {id:"drplFacility_item_217", value:"GH12", text:"Skönstaholmsskolan"},
  {id:"drplFacility_item_218", value:"GM14", text:"Slättgårdsskolan"},
  {id:"drplFacility_item_219", value:"KP14", text:"Smedshagens BP"},
  {id:"drplFacility_item_220", value:"IP14", text:"Smedshagshallen"},
  {id:"drplFacility_item_221", value:"GO22", text:"Smedslättsskolan"},
  {id:"drplFacility_item_222", value:"GD52", text:"Sofia Skola"},
  {id:"drplFacility_item_223", value:"KD52", text:"Sofiaskolans BP"},
  {id:"drplFacility_item_224", value:"KL51", text:"Solberga BP"},
  {id:"drplFacility_item_225", value:"GL51", text:"Solbergaskolan"},
  {id:"drplFacility_item_226", value:"KQ24", text:"Solhems BP"},
  {id:"drplFacility_item_227", value:"IQ22", text:"Spånga Idrottshall"},
  {id:"drplFacility_item_228", value:"KQ23", text:"Spånga IP"},
  {id:"drplFacility_item_229", value:"IQ21", text:"Spångabadet"},
  {id:"drplFacility_item_230", value:"KA82", text:"Stadshagens IP"},
  {id:"drplFacility_item_231", value:"KR02", text:"Stenhagens BP"},
  {id:"drplFacility_item_232", value:"KH11", text:"Stockholm BMX Arena"},
  {id:"drplFacility_item_233", value:"KA91", text:"Stora Essinge IP"},
  {id:"drplFacility_item_234", value:"IO11", text:"Stora Mossenhallarna idr"},
  {id:"drplFacility_item_235", value:"KO11", text:"Stora Mossens IP"},
  {id:"drplFacility_item_236", value:"GD04", text:"Storkyrkoskolan"},
  {id:"drplFacility_item_237", value:"KK41", text:"Stureby BP"},
  {id:"drplFacility_item_238", value:"GK41", text:"Sturebyskolan"},
  {id:"drplFacility_item_239", value:"KK42", text:"Sturebyskolans BP"},
  {id:"drplFacility_item_240", value:"KQ31", text:"Sundby BP"},
  {id:"drplFacility_item_241", value:"GQ31", text:"Sundbyskolan (gymn)"},
  {id:"drplFacility_item_242", value:"KM22", text:"Sätra BP"},
  {id:"drplFacility_item_243", value:"KM21", text:"Sätra IP"},
  {id:"drplFacility_item_244", value:"KM23", text:"Sätradalens BP"},
  {id:"drplFacility_item_245", value:"IM21", text:"Sätrahallen"},
  {id:"drplFacility_item_246", value:"GM21", text:"Sätraskolan (gymn)"},
  {id:"drplFacility_item_247", value:"GD11", text:"Södermalmsskolan (idrott)"},
  {id:"drplFacility_item_248", value:"SD12", text:"Södra Latins Gymn. (möte)"},
  {id:"drplFacility_item_249", value:"GD12", text:"Södra Latins Gymnasium"},
  {id:"drplFacility_item_250", value:"KO71", text:"Södra Ängby BP"},
  {id:"drplFacility_item_251", value:"GO82", text:"Södra Ängby skola"},
  {id:"drplFacility_item_252", value:"GP41", text:"Sörgårdsskolan"},
  {id:"drplFacility_item_253", value:"KH41", text:"Tallkrogens BP"},
  {id:"drplFacility_item_254", value:"GH41", text:"Tallkrogens Skola"},
  {id:"drplFacility_item_255", value:"KD12", text:"Tantolunden BP"},
  {id:"drplFacility_item_256", value:"IN73", text:"Telefonplanshallen"},
  {id:"drplFacility_item_257", value:"IN52", text:"Tellusborgshallen"},
  {id:"drplFacility_item_258", value:"IQ41", text:"Tenstabadet"},
  {id:"drplFacility_item_259", value:"SS12", text:"Tenstabadet skolsim"},
  {id:"drplFacility_item_260", value:"IQ42", text:"Tenstahallen"},
  {id:"drplFacility_item_261", value:"XA04", text:"Testanläggning PLX"},
  {id:"drplFacility_item_262", value:"XA05", text:"Testanläggning SLX"},
  {id:"drplFacility_item_263", value:"IA81", text:"Thorildshallen"},
  {id:"drplFacility_item_264", value:"KA17", text:"Tillfälliga Haga BP"},
  {id:"drplFacility_item_265", value:"GP32", text:"Trollbodaskolan"},
  {id:"drplFacility_item_266", value:"GD53", text:"Tullgårdsskolan"},
  {id:"drplFacility_item_267", value:"KG33", text:"Tätorps BP"},
  {id:"drplFacility_item_268", value:"GA23", text:"Vasa Real"},
  {id:"drplFacility_item_269", value:"GA22", text:"Vasa Real (Nya)"},
  {id:"drplFacility_item_270", value:"KP71", text:"Vinsta BP"},
  {id:"drplFacility_item_271", value:"GP52", text:"Vinsta grundskola östra"},
  {id:"drplFacility_item_272", value:"IN01", text:"Vintervikshallen"},
  {id:"drplFacility_item_273", value:"KM32", text:"Vårbergs IP"},
  {id:"drplFacility_item_274", value:"KP83", text:"Vällingby BP"},
  {id:"drplFacility_item_275", value:"IP81", text:"Vällingbybadet"},
  {id:"drplFacility_item_276", value:"IP82", text:"Vällingbyhallen"},
  {id:"drplFacility_item_277", value:"GP82", text:"Vällingbyskolan (idrott)"},
  {id:"drplFacility_item_278", value:"KN73", text:"Västberga IP"},
  {id:"drplFacility_item_279", value:"KI13", text:"Västboda BP"},
  {id:"drplFacility_item_280", value:"GM15", text:"Västerholms Friskola"},
  {id:"drplFacility_item_281", value:"KL61", text:"Västertorps BP"},
  {id:"drplFacility_item_282", value:"IN31", text:"Västertorpsbadet"},
  {id:"drplFacility_item_283", value:"IN32", text:"Västertorpshallen"},
  {id:"drplFacility_item_284", value:"GL61", text:"Västertorpsskolan"},
  {id:"drplFacility_item_285", value:"SL61", text:"Västertorpsskolan"},
  {id:"drplFacility_item_286", value:"KD11", text:"Zinkensdamms IP"},
  {id:"drplFacility_item_287", value:"KO46", text:"Åkeshovs BP"},
  {id:"drplFacility_item_288", value:"IO41", text:"Åkeshovsbadet"},
  {id:"drplFacility_item_289", value:"IO42", text:"Åkeshovshallen"},
  {id:"drplFacility_item_290", value:"IM01", text:"Ålgrytes motionsrum"},
  {id:"drplFacility_item_291", value:"GO21", text:"Ålstensskolan"},
  {id:"drplFacility_item_292", value:"GN42", text:"Årstadalsskolan"},
  {id:"drplFacility_item_293", value:"KF02", text:"Årstagårdens BP"},
  {id:"drplFacility_item_294", value:"GF01", text:"Årstaskolan"},
  {id:"drplFacility_item_295", value:"GD44", text:"Åsö Grundskola"},
  {id:"drplFacility_item_296", value:"SD44", text:"Åsö Grundskola skolsalar"},
  {id:"drplFacility_item_297", value:"KL71", text:"Älvsjö IP"},
  {id:"drplFacility_item_298", value:"KO61", text:"Ängby IP"},
  {id:"drplFacility_item_299", value:"GO12", text:"Äppelviksskolan"},
  {id:"drplFacility_item_300", value:"KR24", text:"Ärvinge BP"},
  {id:"drplFacility_item_301", value:"IR21", text:"Ärvingehallen"},
  {id:"drplFacility_item_302", value:"KK51", text:"Örby BP"},
  {id:"drplFacility_item_303", value:"GK51", text:"Örbyskolan"},
  {id:"drplFacility_item_304", value:"GL91", text:"Östbergaskolan"},
  {id:"drplFacility_item_305", value:"SL91", text:"Östbergaskolan (möte)"},
  {id:"drplFacility_item_306", value:"KA12", text:"Östermalms IP"},
  {id:"drplFacility_item_307", value:"GA32", text:"Östermalmsskolan (idrott)"},
  {id:"drplFacility_item_308", value:"KA75", text:"Östra Reals BP"},
  {id:"drplFacility_item_309", value:"GA75", text:"Östra Reals Gym (idrott)"},
  {id:"drplFacility_item_310", value:"SA75", text:"Östra Reals Gym (möte)"},
] as const;

export const FACILITIES_WITH_COORDINATES = [
  {
    id: "drplFacility_item_1",
    value: "KO43",
    text: "Abrahamsberg BP",
    latitude: 59.201,
    longitude: 17.805,
  },
  {
    id: "drplFacility_item_2",
    value: "GO41",
    text: "Abrahamsbergssk. (idrott)",
    latitude: 59.2025,
    longitude: 17.8105,
  },
  {
    id: "drplFacility_item_3",
    value: "SO41",
    text: "Abrahamsbergssk. (möte)",
    latitude: 59.204,
    longitude: 17.816,
  },
  {
    id: "drplFacility_item_4",
    value: "GA01",
    text: "Adolf Fredriks Musikskola",
    latitude: 59.2055,
    longitude: 17.8215,
  },
  {
    id: "drplFacility_item_5",
    value: "GO02",
    text: "Adolfsbergsskolan",
    latitude: 59.207,
    longitude: 17.827,
  },
  {
    id: "drplFacility_item_6",
    value: "GR03",
    text: "Akalla Grundskola",
    latitude: 59.2085,
    longitude: 17.8325,
  },
  {
    id: "drplFacility_item_7",
    value: "KR01",
    text: "Akalla Gårds BP",
    latitude: 59.21,
    longitude: 17.838,
  },
  {
    id: "drplFacility_item_8",
    value: "GO01",
    text: "Alviksskolan",
    latitude: 59.2115,
    longitude: 17.8435,
  },
  {
    id: "drplFacility_item_9",
    value: "KN01",
    text: "Aspuddens IP",
    latitude: 59.213,
    longitude: 17.849,
  },
  {
    id: "drplFacility_item_10",
    value: "GN01",
    text: "Aspuddens Skola",
    latitude: 59.2145,
    longitude: 17.8545,
  },
  {
    id: "drplFacility_item_11",
    value: "KN21",
    text: "Axelsbergs BP",
    latitude: 59.216,
    longitude: 17.86,
  },
  {
    id: "drplFacility_item_12",
    value: "GP33",
    text: "Backluraskolan",
    latitude: 59.2175,
    longitude: 17.8655,
  },
  {
    id: "drplFacility_item_13",
    value: "KG21",
    text: "Bagarmossens BP",
    latitude: 59.219,
    longitude: 17.871,
  },
  {
    id: "drplFacility_item_14",
    value: "GG21",
    text: "Bagarmossens Skola",
    latitude: 59.2205,
    longitude: 17.8765,
  },
  {
    id: "drplFacility_item_15",
    value: "KK02",
    text: "Bandhagens Gymnasium BP",
    latitude: 59.222,
    longitude: 17.882,
  },
  {
    id: "drplFacility_item_16",
    value: "GK02",
    text: "Bandhagens Skola",
    latitude: 59.2235,
    longitude: 17.8875,
  },
  {
    id: "drplFacility_item_17",
    value: "KK03",
    text: "Bandhagens Skola BP",
    latitude: 59.225,
    longitude: 17.893,
  },
  {
    id: "drplFacility_item_18",
    value: "IK01",
    text: "Bandhagshallen",
    latitude: 59.2265,
    longitude: 17.8985,
  },
  {
    id: "drplFacility_item_19",
    value: "IO82",
    text: "Beckombergahallen",
    latitude: 59.228,
    longitude: 17.904,
  },
  {
    id: "drplFacility_item_20",
    value: "KA15",
    text: "Bellevue BP",
    latitude: 59.2295,
    longitude: 17.9095,
  },
  {
    id: "drplFacility_item_21",
    value: "KG22",
    text: "Bergholms BP",
    latitude: 59.231,
    longitude: 17.915,
  },
  {
    id: "drplFacility_item_22",
    value: "GG01",
    text: "Björkhagens Skola (idrott",
    latitude: 59.2325,
    longitude: 17.9205,
  },
  {
    id: "drplFacility_item_23",
    value: "SG01",
    text: "Björkhagens skola (möte)",
    latitude: 59.234,
    longitude: 17.926,
  },
  {
    id: "drplFacility_item_24",
    value: "GP72",
    text: "Björnbodaskolan",
    latitude: 59.2355,
    longitude: 17.9315,
  },
  {
    id: "drplFacility_item_25",
    value: "KO82",
    text: "Blackebergs BP",
    latitude: 59.237,
    longitude: 17.937,
  },
  {
    id: "drplFacility_item_26",
    value: "IO81",
    text: "Blackebergshallen",
    latitude: 59.2385,
    longitude: 17.9425,
  },
  {
    id: "drplFacility_item_27",
    value: "GO83",
    text: "Blackebergsskolan",
    latitude: 59.24,
    longitude: 17.948,
  },
  {
    id: "drplFacility_item_28",
    value: "BBLEK",
    text: "Blekholmsterrassen",
    latitude: 59.2415,
    longitude: 17.9535,
  },
  {
    id: "drplFacility_item_29",
    value: "KM01",
    text: "Bredängs BP",
    latitude: 59.243,
    longitude: 17.959,
  },
  {
    id: "drplFacility_item_30",
    value: "IM03",
    text: "Bredängsbadet",
    latitude: 59.2445,
    longitude: 17.9645,
  },
  {
    id: "drplFacility_item_31",
    value: "IM02",
    text: "Bredängshallen",
    latitude: 59.246,
    longitude: 17.97,
  },
  {
    id: "drplFacility_item_32",
    value: "GO11",
    text: "Bromma Gymnasium",
    latitude: 59.2475,
    longitude: 17.9755,
  },
  {
    id: "drplFacility_item_33",
    value: "KO52",
    text: "Bromma Sportfält",
    latitude: 59.249,
    longitude: 17.981,
  },
  {
    id: "drplFacility_item_34",
    value: "KQ51",
    text: "Bromstens IP",
    latitude: 59.2505,
    longitude: 17.9865,
  },
  {
    id: "drplFacility_item_35",
    value: "GQ51",
    text: "Bromstensskolan",
    latitude: 59.252,
    longitude: 17.992,
  },
  {
    id: "drplFacility_item_36",
    value: "KG23",
    text: "Brotorps BP",
    latitude: 59.2535,
    longitude: 17.9975,
  },
  {
    id: "drplFacility_item_37",
    value: "KN52",
    text: "Brännkyrka BP",
    latitude: 59.255,
    longitude: 18.003,
  },
  {
    id: "drplFacility_item_38",
    value: "IN51",
    text: "Brännkyrkahallen",
    latitude: 59.2565,
    longitude: 18.0085,
  },
  {
    id: "drplFacility_item_39",
    value: "KK04",
    text: "Bäckahagens BP",
    latitude: 59.258,
    longitude: 18.014,
  },
  {
    id: "drplFacility_item_40",
    value: "GK21",
    text: "Bäckahagens Skola",
    latitude: 59.2595,
    longitude: 18.0195,
  },
  {
    id: "drplFacility_item_41",
    value: "KK32",
    text: "Bäverdalens BP",
    latitude: 59.261,
    longitude: 18.025,
  },
  {
    id: "drplFacility_item_42",
    value: "KR13",
    text: "Dalhagens BP",
    latitude: 59.2625,
    longitude: 18.0305,
  },
  {
    id: "drplFacility_item_43",
    value: "GA83",
    text: "Eiraskolan",
    latitude: 59.264,
    longitude: 18.036,
  },
  {
    id: "drplFacility_item_44",
    value: "GN12",
    text: "Ekensbergsskolan",
    latitude: 59.2655,
    longitude: 18.0415,
  },
  {
    id: "drplFacility_item_45",
    value: "KA16",
    text: "Ekhagens BP",
    latitude: 59.267,
    longitude: 18.047,
  },
  {
    id: "drplFacility_item_46",
    value: "KQ45",
    text: "Elinsborgs BP",
    latitude: 59.2685,
    longitude: 18.0525,
  },
  {
    id: "drplFacility_item_47",
    value: "IA12",
    text: "Engelbrektshallen",
    latitude: 59.27,
    longitude: 18.058,
  },
  {
    id: "drplFacility_item_48",
    value: "KF32",
    text: "Enskede IP",
    latitude: 59.2715,
    longitude: 18.0635,
  },
  {
    id: "drplFacility_item_49",
    value: "GF31",
    text: "Enskede Skola (idrott)",
    latitude: 59.273,
    longitude: 18.069,
  },
  {
    id: "drplFacility_item_50",
    value: "GF21",
    text: "Enskedefältets Skola",
    latitude: 59.2745,
    longitude: 18.0745,
  },
  {
    id: "drplFacility_item_51",
    value: "IF12",
    text: "Enskedehallen",
    latitude: 59.276,
    longitude: 18.08,
  },
  {
    id: "drplFacility_item_52",
    value: "KD47",
    text: "Eriksdals BP",
    latitude: 59.2775,
    longitude: 18.0855,
  },
  {
    id: "drplFacility_item_53",
    value: "ID40",
    text: "Eriksdalsbadet",
    latitude: 59.279,
    longitude: 18.091,
  },
  {
    id: "drplFacility_item_54",
    value: "ID42",
    text: "Eriksdalshallen",
    latitude: 59.2805,
    longitude: 18.0965,
  },
  {
    id: "drplFacility_item_55",
    value: "SD41",
    text: "Eriksdalsskolan",
    latitude: 59.282,
    longitude: 18.102,
  },
  {
    id: "drplFacility_item_56",
    value: "GD41",
    text: "Eriksdalsskolan (idrott)",
    latitude: 59.2835,
    longitude: 18.1075,
  },
  {
    id: "drplFacility_item_57",
    value: "GA91",
    text: "Essinge Skola",
    latitude: 59.285,
    longitude: 18.113,
  },
  {
    id: "drplFacility_item_58",
    value: "GI01",
    text: "Fagersjöskolan",
    latitude: 59.2865,
    longitude: 18.1185,
  },
  {
    id: "drplFacility_item_59",
    value: "KI14",
    text: "Farsta IP",
    latitude: 59.288,
    longitude: 18.124,
  },
  {
    id: "drplFacility_item_60",
    value: "II14",
    text: "Farstahallarna, Farsta IP",
    latitude: 59.2895,
    longitude: 18.1295,
  },
  {
    id: "drplFacility_item_61",
    value: "II15",
    text: "Farstahallen",
    latitude: 59.291,
    longitude: 18.135,
  },
  {
    id: "drplFacility_item_62",
    value: "ID44",
    text: "Forsgrenska",
    latitude: 59.2925,
    longitude: 18.1405,
  },
  {
    id: "drplFacility_item_63",
    value: "ID43",
    text: "Forsgrenskabadet",
    latitude: 59.294,
    longitude: 18.146,
  },
  {
    id: "drplFacility_item_64",
    value: "KL01",
    text: "Fruängens BP",
    latitude: 59.2955,
    longitude: 18.1515,
  },
  {
    id: "drplFacility_item_65",
    value: "GL01",
    text: "Fruängens Skola (idrott)",
    latitude: 59.297,
    longitude: 18.157,
  },
  {
    id: "drplFacility_item_66",
    value: "IA11",
    text: "GIH-badet",
    latitude: 59.2985,
    longitude: 18.1625,
  },
  {
    id: "drplFacility_item_67",
    value: "GD05",
    text: "Globala gymnasiet",
    latitude: 59.3,
    longitude: 18.168,
  },
  {
    id: "drplFacility_item_68",
    value: "KQ20",
    text: "Gläntans IP",
    latitude: 59.3015,
    longitude: 18.1735,
  },
  {
    id: "drplFacility_item_69",
    value: "KR03",
    text: "Granby BP",
    latitude: 59.303,
    longitude: 18.179,
  },
  {
    id: "drplFacility_item_70",
    value: "KP02",
    text: "Grimsta BP",
    latitude: 59.3045,
    longitude: 18.1845,
  },
  {
    id: "drplFacility_item_71",
    value: "KP01",
    text: "Grimsta IP",
    latitude: 59.306,
    longitude: 18.19,
  },
  {
    id: "drplFacility_item_72",
    value: "IP01",
    text: "Grimstahallen",
    latitude: 59.3075,
    longitude: 18.1955,
  },
  {
    id: "drplFacility_item_73",
    value: "KN11",
    text: "Gröndals BP",
    latitude: 59.309,
    longitude: 18.201,
  },
  {
    id: "drplFacility_item_74",
    value: "KH04",
    text: "Gubbängens BP",
    latitude: 59.3105,
    longitude: 18.2065,
  },
  {
    id: "drplFacility_item_75",
    value: "KH01",
    text: "Gubbängens IP",
    latitude: 59.312,
    longitude: 18.212,
  },
  {
    id: "drplFacility_item_76",
    value: "KH02",
    text: "Gubbängens Sportfält",
    latitude: 59.3135,
    longitude: 18.2175,
  },
  {
    id: "drplFacility_item_77",
    value: "GH01",
    text: "Gubbängsbadet",
    latitude: 59.315,
    longitude: 18.223,
  },
  {
    id: "drplFacility_item_78",
    value: "KH03",
    text: "Gubbängsfältet Rugby",
    latitude: 59.3165,
    longitude: 18.2285,
  },
  {
    id: "drplFacility_item_79",
    value: "IH02",
    text: "Gubbängshallen",
    latitude: 59.318,
    longitude: 18.234,
  },
  {
    id: "drplFacility_item_80",
    value: "GH02",
    text: "Gubbängsskolan (idrott)",
    latitude: 59.3195,
    longitude: 18.2395,
  },
  {
    id: "drplFacility_item_81",
    value: "GQ44",
    text: "Gullingeskolan",
    latitude: 59.321,
    longitude: 18.245,
  },
  {
    id: "drplFacility_item_82",
    value: "GA21",
    text: "Gustav Vasa Skola (idrott",
    latitude: 59.3225,
    longitude: 18.2505,
  },
  {
    id: "drplFacility_item_83",
    value: "IA31",
    text: "Gärdeshallen",
    latitude: 59.324,
    longitude: 18.256,
  },
  {
    id: "drplFacility_item_84",
    value: "SA71",
    text: "Gärdesskolan (klassrum)",
    latitude: 59.3255,
    longitude: 18.2615,
  },
  {
    id: "drplFacility_item_85",
    value: "KA31",
    text: "Gärdesskolans bollplan",
    latitude: 59.327,
    longitude: 18.267,
  },
  {
    id: "drplFacility_item_86",
    value: "KA71",
    text: "Gärdets Sportfält",
    latitude: 59.3285,
    longitude: 18.2725,
  },
  {
    id: "drplFacility_item_87",
    value: "KK12",
    text: "Hagsätra IP",
    latitude: 59.33,
    longitude: 18.278,
  },
  {
    id: "drplFacility_item_88",
    value: "IK25",
    text: "Hagsätrahallen",
    latitude: 59.3315,
    longitude: 18.2835,
  },
  {
    id: "drplFacility_item_89",
    value: "KD50",
    text: "Hammarby IP",
    latitude: 59.333,
    longitude: 18.289,
  },
  {
    id: "drplFacility_item_90",
    value: "GG03",
    text: "Hammarby Skola Norra",
    latitude: 59.3345,
    longitude: 18.2945,
  },
  {
    id: "drplFacility_item_91",
    value: "KG01",
    text: "Hammarbyhöjden IP",
    latitude: 59.336,
    longitude: 18.3,
  },
  {
    id: "drplFacility_item_92",
    value: "GG02",
    text: "Hammarbyskolan Södra",
    latitude: 59.3375,
    longitude: 18.3055,
  },
  {
    id: "drplFacility_item_93",
    value: "KL11",
    text: "Herrängens BP",
    latitude: 59.339,
    longitude: 18.311,
  },
  {
    id: "drplFacility_item_94",
    value: "GL11",
    text: "Herrängens Skola",
    latitude: 59.3405,
    longitude: 18.3165,
  },
  {
    id: "drplFacility_item_95",
    value: "KA13",
    text: "Hjorthagens IP",
    latitude: 59.342,
    longitude: 18.322,
  },
  {
    id: "drplFacility_item_96",
    value: "IA13",
    text: "Hjorthagshallen",
    latitude: 59.3435,
    longitude: 18.3275,
  },
  {
    id: "drplFacility_item_97",
    value: "KQ44",
    text: "Hjulsta BP",
    latitude: 59.345,
    longitude: 18.333,
  },
  {
    id: "drplFacility_item_98",
    value: "GQ47",
    text: "Hjulstaskolan (idrott)",
    latitude: 59.3465,
    longitude: 18.3385,
  },
  {
    id: "drplFacility_item_99",
    value: "KR12",
    text: "Husby BP",
    latitude: 59.348,
    longitude: 18.344,
  },
  {
    id: "drplFacility_item_100",
    value: "KR11",
    text: "Husby Ishall",
    latitude: 59.3495,
    longitude: 18.3495,
  },
  {
    id: "drplFacility_item_101",
    value: "IR10",
    text: "Husbybadet",
    latitude: 59.351,
    longitude: 18.355,
  },
  {
    id: "drplFacility_item_102",
    value: "SS13",
    text: "Husbybadet skolsim",
    latitude: 59.3525,
    longitude: 18.3605,
  },
  {
    id: "drplFacility_item_103",
    value: "GR13",
    text: "Husbygårdsskolan",
    latitude: 59.354,
    longitude: 18.366,
  },
  {
    id: "drplFacility_item_104",
    value: "IR11",
    text: "Husbyhallen",
    latitude: 59.3555,
    longitude: 18.3715,
  },
  {
    id: "drplFacility_item_105",
    value: "GN32",
    text: "Hägerstenshamnens Skola",
    latitude: 59.357,
    longitude: 18.377,
  },
  {
    id: "drplFacility_item_106",
    value: "KN33",
    text: "Hägerstensåsens BP",
    latitude: 59.3585,
    longitude: 18.3825,
  },
  {
    id: "drplFacility_item_107",
    value: "GN31",
    text: "Hägerstensåsens Skola",
    latitude: 59.36,
    longitude: 18.388,
  },
  {
    id: "drplFacility_item_108",
    value: "KP11",
    text: "Hässelby Gårds BP",
    latitude: 59.3615,
    longitude: 18.3935,
  },
  {
    id: "drplFacility_item_109",
    value: "KP10",
    text: "Hässelby IP",
    latitude: 59.363,
    longitude: 18.399,
  },
  {
    id: "drplFacility_item_110",
    value: "KP31",
    text: "Hässelby Villastads BP",
    latitude: 59.3645,
    longitude: 18.4045,
  },
  {
    id: "drplFacility_item_111",
    value: "GP11",
    text: "Hässelbygårdssk. (idrott)",
    latitude: 59.366,
    longitude: 18.41,
  },
  {
    id: "drplFacility_item_112",
    value: "SP11",
    text: "Hässelbygårdsskolan",
    latitude: 59.3675,
    longitude: 18.4155,
  },
  {
    id: "drplFacility_item_113",
    value: "IP31",
    text: "Hässelbyhallen",
    latitude: 59.369,
    longitude: 18.421,
  },
  {
    id: "drplFacility_item_114",
    value: "KP24",
    text: "Hässelängens BP",
    latitude: 59.3705,
    longitude: 18.4265,
  },
  {
    id: "drplFacility_item_115",
    value: "KI11",
    text: "Hästhagens BP",
    latitude: 59.372,
    longitude: 18.432,
  },
  {
    id: "drplFacility_item_116",
    value: "GI13",
    text: "Hästhagsskolan",
    latitude: 59.3735,
    longitude: 18.4375,
  },
  {
    id: "drplFacility_item_117",
    value: "GD01",
    text: "Högalidsskolan (idrott)",
    latitude: 59.375,
    longitude: 18.443,
  },
  {
    id: "drplFacility_item_118",
    value: "KK23",
    text: "Högdalens BP",
    latitude: 59.3765,
    longitude: 18.4485,
  },
  {
    id: "drplFacility_item_119",
    value: "IK21",
    text: "Högdalsbadet",
    latitude: 59.378,
    longitude: 18.454,
  },
  {
    id: "drplFacility_item_120",
    value: "IK22",
    text: "Högdalshallen",
    latitude: 59.3795,
    longitude: 18.4595,
  },
  {
    id: "drplFacility_item_121",
    value: "SO23",
    text: "Höglandsskolan",
    latitude: 59.381,
    longitude: 18.465,
  },
  {
    id: "drplFacility_item_122",
    value: "KH12",
    text: "Hökarängens BP",
    latitude: 59.3825,
    longitude: 18.4705,
  },
  {
    id: "drplFacility_item_123",
    value: "KH14",
    text: "Hökarängens BP",
    latitude: 59.384,
    longitude: 18.476,
  },
  {
    id: "drplFacility_item_124",
    value: "GH11",
    text: "Hökarängsskolan (idrott)",
    latitude: 59.3855,
    longitude: 18.4815,
  },
  {
    id: "drplFacility_item_125",
    value: "GL31",
    text: "Johan Skyttesk. (idrott)",
    latitude: 59.387,
    longitude: 18.487,
  },
  {
    id: "drplFacility_item_126",
    value: "SL31",
    text: "Johan Skyttesk. (möte)",
    latitude: 59.3885,
    longitude: 18.4925,
  },
  {
    id: "drplFacility_item_127",
    value: "KA22",
    text: "Johannes BP",
    latitude: 59.39,
    longitude: 18.498,
  },
  {
    id: "drplFacility_item_128",
    value: "GA41",
    text: "Johannes Skola",
    latitude: 59.3915,
    longitude: 18.5035,
  },
  {
    id: "drplFacility_item_129",
    value: "KM31",
    text: "Johannesdal BP",
    latitude: 59.393,
    longitude: 18.509,
  },
  {
    id: "drplFacility_item_130",
    value: "ID50",
    text: "Kanalhallen",
    latitude: 59.3945,
    longitude: 18.5145,
  },
  {
    id: "drplFacility_item_131",
    value: "GA24",
    text: "Karlbergs skola",
    latitude: 59.396,
    longitude: 18.52,
  },
  {
    id: "drplFacility_item_132",
    value: "GD42",
    text: "Katarina Norra Skola",
    latitude: 59.3975,
    longitude: 18.5255,
  },
  {
    id: "drplFacility_item_133",
    value: "KD43",
    text: "Katarina Södra BP",
    latitude: 59.399,
    longitude: 18.531,
  },
  {
    id: "drplFacility_item_134",
    value: "GD43",
    text: "Katarina Södra Skola",
    latitude: 59.4005,
    longitude: 18.5365,
  },
  {
    id: "drplFacility_item_135",
    value: "GA81",
    text: "Klastorpsskolan",
    latitude: 59.402,
    longitude: 18.542,
  },
  {
    id: "drplFacility_item_136",
    value: "KQ61",
    text: "Knutby BP",
    latitude: 59.4035,
    longitude: 18.5475,
  },
  {
    id: "drplFacility_item_137",
    value: "GQ30",
    text: "Knutbyskolan",
    latitude: 59.405,
    longitude: 18.553,
  },
  {
    id: "drplFacility_item_138",
    value: "IA82",
    text: "Konradsbergshallen",
    latitude: 59.4065,
    longitude: 18.5585,
  },
  {
    id: "drplFacility_item_139",
    value: "KA83",
    text: "Kristinebergs IP",
    latitude: 59.408,
    longitude: 18.564,
  },
  {
    id: "drplFacility_item_140",
    value: "GA92",
    text: "Kristinebergsskolan",
    latitude: 59.4095,
    longitude: 18.5695,
  },
  {
    id: "drplFacility_item_141",
    value: "IA61",
    text: "Kronobergsbadet",
    latitude: 59.411,
    longitude: 18.575,
  },
  {
    id: "drplFacility_item_142",
    value: "GA87",
    text: "Kungsholmens Grund Nya",
    latitude: 59.4125,
    longitude: 18.5805,
  },
  {
    id: "drplFacility_item_143",
    value: "GA88",
    text: "Kungsholmens Grundskola",
    latitude: 59.414,
    longitude: 18.586,
  },
  {
    id: "drplFacility_item_144",
    value: "GA82",
    text: "Kungsholmens Gym. (idrott)",
    latitude: 59.4155,
    longitude: 18.5915,
  },
  {
    id: "drplFacility_item_145",
    value: "SA82",
    text: "Kungsholmens Gym. (möte)",
    latitude: 59.417,
    longitude: 18.597,
  },
  {
    id: "drplFacility_item_146",
    value: "KA81",
    text: "Kungsholmens Gymnasium BP",
    latitude: 59.4185,
    longitude: 18.6025,
  },
  {
    id: "drplFacility_item_147",
    value: "KR23",
    text: "Kvarnbacka BP",
    latitude: 59.42,
    longitude: 18.608,
  },
  {
    id: "drplFacility_item_148",
    value: "GR22",
    text: "Kvarnbackaskolan",
    latitude: 59.4215,
    longitude: 18.6135,
  },
  {
    id: "drplFacility_item_149",
    value: "GQ63",
    text: "Kvarnbyskolan",
    latitude: 59.423,
    longitude: 18.619,
  },
  {
    id: "drplFacility_item_150",
    value: "KI12",
    text: "Kvickentorps BP",
    latitude: 59.4245,
    longitude: 18.6245,
  },
  {
    id: "drplFacility_item_151",
    value: "KP41",
    text: "Kälvesta BP",
    latitude: 59.426,
    longitude: 18.63,
  },
  {
    id: "drplFacility_item_152",
    value: "KL33",
    text: "Kämpetorps BP",
    latitude: 59.4275,
    longitude: 18.6355,
  },
  {
    id: "drplFacility_item_153",
    value: "IL33",
    text: "Kämpetorpshallen",
    latitude: 59.429,
    longitude: 18.641,
  },
  {
    id: "drplFacility_item_154",
    value: "KG11",
    text: "Kärrtorps IP",
    latitude: 59.4305,
    longitude: 18.6465,
  },
  {
    id: "drplFacility_item_155",
    value: "IG11",
    text: "Kärrtorpshallen",
    latitude: 59.432,
    longitude: 18.652,
  },
  {
    id: "drplFacility_item_156",
    value: "IN42",
    text: "Liljeholmshallen",
    latitude: 59.4335,
    longitude: 18.6575,
  },
  {
    id: "drplFacility_item_157",
    value: "GA02",
    text: "Lilla Adolf Fredrik Skola",
    latitude: 59.435,
    longitude: 18.663,
  },
  {
    id: "drplFacility_item_158",
    value: "GF20",
    text: "Lindeskolan",
    latitude: 59.4365,
    longitude: 18.6685,
  },
  {
    id: "drplFacility_item_159",
    value: "KL21",
    text: "Lisebergs BP",
    latitude: 59.438,
    longitude: 18.674,
  },
  {
    id: "drplFacility_item_160",
    value: "GP12",
    text: "Loviselundsskolan",
    latitude: 59.4395,
    longitude: 18.6795,
  },
  {
    id: "drplFacility_item_161",
    value: "KL34",
    text: "Långbro BP",
    latitude: 59.441,
    longitude: 18.685,
  },
  {
    id: "drplFacility_item_162",
    value: "GL32",
    text: "Långbrodals Gamla Skola",
    latitude: 59.4425,
    longitude: 18.6905,
  },
  {
    id: "drplFacility_item_163",
    value: "KD01",
    text: "Långholmens BP",
    latitude: 59.444,
    longitude: 18.696,
  },
  {
    id: "drplFacility_item_164",
    value: "GI21",
    text: "Magelungsskolan",
    latitude: 59.4455,
    longitude: 18.7015,
  },
  {
    id: "drplFacility_item_165",
    value: "KP23",
    text: "Maltesholmsskolans BP",
    latitude: 59.447,
    longitude: 18.707,
  },
  {
    id: "drplFacility_item_166",
    value: "GD02",
    text: "Maria Skola",
    latitude: 59.4485,
    longitude: 18.7125,
  },
  {
    id: "drplFacility_item_167",
    value: "GA61",
    text: "Matteusskolan (idrott)",
    latitude: 59.45,
    longitude: 18.718,
  },
  {
    id: "drplFacility_item_168",
    value: "SA61",
    text: "Matteusskolan (möte)",
    latitude: 59.4515,
    longitude: 18.7235,
  },
  {
    id: "drplFacility_item_169",
    value: "KQ25",
    text: "Mellangårdens BP",
    latitude: 59.453,
    longitude: 18.729,
  },
  {
    id: "drplFacility_item_170",
    value: "IL02",
    text: "Mälarhöjden Gymnastikhall",
    latitude: 59.4545,
    longitude: 18.7345,
  },
  {
    id: "drplFacility_item_171",
    value: "KL02",
    text: "Mälarhöjdens IP",
    latitude: 59.456,
    longitude: 18.74,
  },
  {
    id: "drplFacility_item_172",
    value: "GN61",
    text: "Mälarhöjdens Skola (idr)",
    latitude: 59.4575,
    longitude: 18.7455,
  },
  {
    id: "drplFacility_item_173",
    value: "KO31",
    text: "Nockebyhovs BP",
    latitude: 59.459,
    longitude: 18.751,
  },
  {
    id: "drplFacility_item_174",
    value: "KA43",
    text: "Norra Reals Bollplan",
    latitude: 59.4605,
    longitude: 18.7565,
  },
  {
    id: "drplFacility_item_175",
    value: "GA43",
    text: "Norra Reals Gymn (idrott)",
    latitude: 59.462,
    longitude: 18.762,
  },
  {
    id: "drplFacility_item_176",
    value: "SA43",
    text: "Norra Reals Gymn (möte)",
    latitude: 59.4635,
    longitude: 18.7675,
  },
  {
    id: "drplFacility_item_177",
    value: "GO61",
    text: "Norra Ängby Skola",
    latitude: 59.465,
    longitude: 18.773,
  },
  {
    id: "drplFacility_item_178",
    value: "KO44",
    text: "Nya Element BP",
    latitude: 59.4665,
    longitude: 18.7785,
  },
  {
    id: "drplFacility_item_179",
    value: "GN41",
    text: "Nybohovsskolan",
    latitude: 59.468,
    longitude: 18.784,
  },
  {
    id: "drplFacility_item_180",
    value: "KG03",
    text: "Nytorps BP",
    latitude: 59.4695,
    longitude: 18.7895,
  },
  {
    id: "drplFacility_item_181",
    value: "KP51",
    text: "Nälsta BP",
    latitude: 59.471,
    longitude: 18.795,
  },
  {
    id: "drplFacility_item_182",
    value: "IP52",
    text: "Nälstabadet",
    latitude: 59.4725,
    longitude: 18.8005,
  },
  {
    id: "drplFacility_item_183",
    value: "GP51",
    text: "Nälstaskolan",
    latitude: 59.474,
    longitude: 18.806,
  },
  {
    id: "drplFacility_item_184",
    value: "KO32",
    text: "Olovslunds BP",
    latitude: 59.4755,
    longitude: 18.8115,
  },
  {
    id: "drplFacility_item_185",
    value: "GO32",
    text: "Olovslundsskolan",
    latitude: 59.477,
    longitude: 18.817,
  },
  {
    id: "drplFacility_item_186",
    value: "KK13",
    text: "Ormkärrs BP",
    latitude: 59.4785,
    longitude: 18.8225,
  },
  {
    id: "drplFacility_item_187",
    value: "GK12",
    text: "Ormkärrsskolan (idrott)",
    latitude: 59.48,
    longitude: 18.828,
  },
  {
    id: "drplFacility_item_188",
    value: "IP32",
    text: "Riddersvikshallen",
    latitude: 59.4815,
    longitude: 18.8335,
  },
  {
    id: "drplFacility_item_189",
    value: "KQ62",
    text: "Rinkeby BP",
    latitude: 59.483,
    longitude: 18.839,
  },
  {
    id: "drplFacility_item_190",
    value: "IQ62",
    text: "Rinkebyhallen",
    latitude: 59.4845,
    longitude: 18.8445,
  },
  {
    id: "drplFacility_item_191",
    value: "SQ61",
    text: "Rinkebyskolan",
    latitude: 59.486,
    longitude: 18.85,
  },
  {
    id: "drplFacility_item_192",
    value: "KK31",
    text: "Rågsveds BP",
    latitude: 59.4875,
    longitude: 18.8555,
  },
  {
    id: "drplFacility_item_193",
    value: "GK31",
    text: "Rågsvedsskolan",
    latitude: 59.489,
    longitude: 18.861,
  },
  {
    id: "drplFacility_item_194",
    value: "GA84",
    text: "Rålambshovsskolan",
    latitude: 59.4905,
    longitude: 18.8665,
  },
  {
    id: "drplFacility_item_195",
    value: "IA22",
    text: "Rödabergshallen",
    latitude: 59.492,
    longitude: 18.872,
  },
  {
    id: "drplFacility_item_196",
    value: "IA41",
    text: "S:t Erikshallen",
    latitude: 59.4935,
    longitude: 18.8775,
  },
  {
    id: "drplFacility_item_197",
    value: "KH21",
    text: "Sandåkra BP",
    latitude: 59.495,
    longitude: 18.883,
  },
  {
    id: "drplFacility_item_198",
    value: "GH22",
    text: "Sandåkraskolan",
    latitude: 59.4965,
    longitude: 18.8885,
  },
  {
    id: "drplFacility_item_199",
    value: "IE51",
    text: "Sjöstadshallen",
    latitude: 59.498,
    longitude: 18.894,
  },
  {
    id: "drplFacility_item_200",
    value: "GE51",
    text: "Sjöstadsskolan",
    latitude: 59.4995,
    longitude: 18.8995,
  },
  {
    id: "drplFacility_item_201",
    value: "IF01",
    text: "Sjöviksskolan",
    latitude: 59.501,
    longitude: 18.905,
  },
  {
    id: "drplFacility_item_202",
    value: "KL81",
    text: "Sjöängens BP",
    latitude: 59.5025,
    longitude: 18.9105,
  },
  {
    id: "drplFacility_item_203",
    value: "GL81",
    text: "Sjöängsskolan",
    latitude: 59.504,
    longitude: 18.916,
  },
  {
    id: "drplFacility_item_204",
    value: "IF14",
    text: "Skanskvarnshallen",
    latitude: 59.5055,
    longitude: 18.9215,
  },
  {
    id: "drplFacility_item_205",
    value: "GF12",
    text: "Skanskvarnsskolan (idrott)",
    latitude: 59.507,
    longitude: 18.927,
  },
  {
    id: "drplFacility_item_206",
    value: "ID51",
    text: "Skanstullshallen",
    latitude: 59.5085,
    longitude: 18.9325,
  },
  {
    id: "drplFacility_item_207",
    value: "GG31",
    text: "Skarpatorpsskolan F-3",
    latitude: 59.51,
    longitude: 18.938,
  },
  {
    id: "drplFacility_item_208",
    value: "KG12",
    text: "Skarpnäcks BP",
    latitude: 59.5115,
    longitude: 18.9435,
  },
  {
    id: "drplFacility_item_209",
    value: "GG12",
    text: "Skarpnäcks Skola",
    latitude: 59.513,
    longitude: 18.949,
  },
  {
    id: "drplFacility_item_210",
    value: "KG32",
    text: "Skarpnäcks Sportfält",
    latitude: 59.5145,
    longitude: 18.9545,
  },
  {
    id: "drplFacility_item_211",
    value: "IG32",
    text: "Skarpnäckshallen",
    latitude: 59.516,
    longitude: 18.96,
  },
  {
    id: "drplFacility_item_212",
    value: "SM12",
    text: "Skärholmens gymnasium",
    latitude: 59.5175,
    longitude: 18.9655,
  },
  {
    id: "drplFacility_item_213",
    value: "IM11",
    text: "Skärholmsbadet",
    latitude: 59.519,
    longitude: 18.971,
  },
  {
    id: "drplFacility_item_214",
    value: "IM12",
    text: "Skärholmshallen",
    latitude: 59.5205,
    longitude: 18.9765,
  },
  {
    id: "drplFacility_item_215",
    value: "KH22",
    text: "Sköndals BP",
    latitude: 59.522,
    longitude: 18.982,
  },
  {
    id: "drplFacility_item_216",
    value: "IH21",
    text: "Sköndalshallen",
    latitude: 59.5235,
    longitude: 18.9875,
  },
  {
    id: "drplFacility_item_217",
    value: "GH12",
    text: "Skönstaholmsskolan",
    latitude: 59.525,
    longitude: 18.993,
  },
  {
    id: "drplFacility_item_218",
    value: "GM14",
    text: "Slättgårdsskolan",
    latitude: 59.5265,
    longitude: 18.9985,
  },
  {
    id: "drplFacility_item_219",
    value: "KP14",
    text: "Smedshagens BP",
    latitude: 59.528,
    longitude: 19.004,
  },
  {
    id: "drplFacility_item_220",
    value: "IP14",
    text: "Smedshagshallen",
    latitude: 59.5295,
    longitude: 19.0095,
  },
  {
    id: "drplFacility_item_221",
    value: "GO22",
    text: "Smedslättsskolan",
    latitude: 59.531,
    longitude: 19.015,
  },
  {
    id: "drplFacility_item_222",
    value: "GD52",
    text: "Sofia Skola",
    latitude: 59.5325,
    longitude: 19.0205,
  },
  {
    id: "drplFacility_item_223",
    value: "KD52",
    text: "Sofiaskolans BP",
    latitude: 59.534,
    longitude: 19.026,
  },
  {
    id: "drplFacility_item_224",
    value: "KL51",
    text: "Solberga BP",
    latitude: 59.5355,
    longitude: 19.0315,
  },
  {
    id: "drplFacility_item_225",
    value: "GL51",
    text: "Solbergaskolan",
    latitude: 59.537,
    longitude: 19.037,
  },
  {
    id: "drplFacility_item_226",
    value: "KQ24",
    text: "Solhems BP",
    latitude: 59.5385,
    longitude: 19.0425,
  },
  {
    id: "drplFacility_item_227",
    value: "IQ22",
    text: "Spånga Idrottshall",
    latitude: 59.54,
    longitude: 19.048,
  },
  {
    id: "drplFacility_item_228",
    value: "KQ23",
    text: "Spånga IP",
    latitude: 59.5415,
    longitude: 19.0535,
  },
  {
    id: "drplFacility_item_229",
    value: "IQ21",
    text: "Spångabadet",
    latitude: 59.543,
    longitude: 19.059,
  },
  {
    id: "drplFacility_item_230",
    value: "KA82",
    text: "Stadshagens IP",
    latitude: 59.5445,
    longitude: 19.0645,
  },
  {
    id: "drplFacility_item_231",
    value: "KR02",
    text: "Stenhagens BP",
    latitude: 59.546,
    longitude: 19.07,
  },
  {
    id: "drplFacility_item_232",
    value: "KH11",
    text: "Stockholm BMX Arena",
    latitude: 59.5475,
    longitude: 19.0755,
  },
  {
    id: "drplFacility_item_233",
    value: "KA91",
    text: "Stora Essinge IP",
    latitude: 59.549,
    longitude: 19.081,
  },
  {
    id: "drplFacility_item_234",
    value: "IO11",
    text: "Stora Mossenhallarna idr",
    latitude: 59.5505,
    longitude: 19.0865,
  },
  {
    id: "drplFacility_item_235",
    value: "KO11",
    text: "Stora Mossens IP",
    latitude: 59.552,
    longitude: 19.092,
  },
  {
    id: "drplFacility_item_236",
    value: "GD04",
    text: "Storkyrkoskolan",
    latitude: 59.5535,
    longitude: 19.0975,
  },
  {
    id: "drplFacility_item_237",
    value: "KK41",
    text: "Stureby BP",
    latitude: 59.555,
    longitude: 19.103,
  },
  {
    id: "drplFacility_item_238",
    value: "GK41",
    text: "Sturebyskolan",
    latitude: 59.5565,
    longitude: 19.1085,
  },
  {
    id: "drplFacility_item_239",
    value: "KK42",
    text: "Sturebyskolans BP",
    latitude: 59.558,
    longitude: 19.114,
  },
  {
    id: "drplFacility_item_240",
    value: "KQ31",
    text: "Sundby BP",
    latitude: 59.5595,
    longitude: 19.1195,
  },
  {
    id: "drplFacility_item_241",
    value: "GQ31",
    text: "Sundbyskolan (gymn)",
    latitude: 59.561,
    longitude: 19.125,
  },
  {
    id: "drplFacility_item_242",
    value: "KM22",
    text: "Sätra BP",
    latitude: 59.5625,
    longitude: 19.1305,
  },
  {
    id: "drplFacility_item_243",
    value: "KM21",
    text: "Sätra IP",
    latitude: 59.564,
    longitude: 19.136,
  },
  {
    id: "drplFacility_item_244",
    value: "KM23",
    text: "Sätradalens BP",
    latitude: 59.5655,
    longitude: 19.1415,
  },
  {
    id: "drplFacility_item_245",
    value: "IM21",
    text: "Sätrahallen",
    latitude: 59.567,
    longitude: 19.147,
  },
  {
    id: "drplFacility_item_246",
    value: "GM21",
    text: "Sätraskolan (gymn)",
    latitude: 59.5685,
    longitude: 19.1525,
  },
  {
    id: "drplFacility_item_247",
    value: "GD11",
    text: "Södermalmsskolan (idrott)",
    latitude: 59.57,
    longitude: 19.158,
  },
  {
    id: "drplFacility_item_248",
    value: "SD12",
    text: "Södra Latins Gymn. (möte)",
    latitude: 59.5715,
    longitude: 19.1635,
  },
  {
    id: "drplFacility_item_249",
    value: "GD12",
    text: "Södra Latins Gymnasium",
    latitude: 59.573,
    longitude: 19.169,
  },
  {
    id: "drplFacility_item_250",
    value: "KO71",
    text: "Södra Ängby BP",
    latitude: 59.5745,
    longitude: 19.1745,
  },
  {
    id: "drplFacility_item_251",
    value: "GO82",
    text: "Södra Ängby skola",
    latitude: 59.576,
    longitude: 19.18,
  },
  {
    id: "drplFacility_item_252",
    value: "GP41",
    text: "Sörgårdsskolan",
    latitude: 59.5775,
    longitude: 19.1855,
  },
  {
    id: "drplFacility_item_253",
    value: "KH41",
    text: "Tallkrogens BP",
    latitude: 59.579,
    longitude: 19.191,
  },
  {
    id: "drplFacility_item_254",
    value: "GH41",
    text: "Tallkrogens Skola",
    latitude: 59.5805,
    longitude: 19.1965,
  },
  {
    id: "drplFacility_item_255",
    value: "KD12",
    text: "Tantolunden BP",
    latitude: 59.582,
    longitude: 19.202,
  },
  {
    id: "drplFacility_item_256",
    value: "IN73",
    text: "Telefonplanshallen",
    latitude: 59.5835,
    longitude: 19.2075,
  },
  {
    id: "drplFacility_item_257",
    value: "IN52",
    text: "Tellusborgshallen",
    latitude: 59.585,
    longitude: 19.213,
  },
  {
    id: "drplFacility_item_258",
    value: "IQ41",
    text: "Tenstabadet",
    latitude: 59.5865,
    longitude: 19.2185,
  },
  {
    id: "drplFacility_item_259",
    value: "SS12",
    text: "Tenstabadet skolsim",
    latitude: 59.588,
    longitude: 19.224,
  },
  {
    id: "drplFacility_item_260",
    value: "IQ42",
    text: "Tenstahallen",
    latitude: 59.5895,
    longitude: 19.2295,
  },
  {
    id: "drplFacility_item_261",
    value: "XA04",
    text: "Testanläggning PLX",
    latitude: 59.591,
    longitude: 19.235,
  },
  {
    id: "drplFacility_item_262",
    value: "XA05",
    text: "Testanläggning SLX",
    latitude: 59.5925,
    longitude: 19.2405,
  },
  {
    id: "drplFacility_item_263",
    value: "IA81",
    text: "Thorildshallen",
    latitude: 59.594,
    longitude: 19.246,
  },
  {
    id: "drplFacility_item_264",
    value: "KA17",
    text: "Tillfälliga Haga BP",
    latitude: 59.5955,
    longitude: 19.2515,
  },
  {
    id: "drplFacility_item_265",
    value: "GP32",
    text: "Trollbodaskolan",
    latitude: 59.597,
    longitude: 19.257,
  },
  {
    id: "drplFacility_item_266",
    value: "GD53",
    text: "Tullgårdsskolan",
    latitude: 59.5985,
    longitude: 19.2625,
  },
  {
    id: "drplFacility_item_267",
    value: "KG33",
    text: "Tätorps BP",
    latitude: 59.6,
    longitude: 19.268,
  },
  {
    id: "drplFacility_item_268",
    value: "GA23",
    text: "Vasa Real",
    latitude: 59.6015,
    longitude: 19.2735,
  },
  {
    id: "drplFacility_item_269",
    value: "GA22",
    text: "Vasa Real (Nya)",
    latitude: 59.603,
    longitude: 19.279,
  },
  {
    id: "drplFacility_item_270",
    value: "KP71",
    text: "Vinsta BP",
    latitude: 59.6045,
    longitude: 19.2845,
  },
  {
    id: "drplFacility_item_271",
    value: "GP52",
    text: "Vinsta grundskola östra",
    latitude: 59.606,
    longitude: 19.29,
  },
  {
    id: "drplFacility_item_272",
    value: "IN01",
    text: "Vintervikshallen",
    latitude: 59.6075,
    longitude: 19.2955,
  },
  {
    id: "drplFacility_item_273",
    value: "KM32",
    text: "Vårbergs IP",
    latitude: 59.609,
    longitude: 19.301,
  },
  {
    id: "drplFacility_item_274",
    value: "KP83",
    text: "Vällingby BP",
    latitude: 59.6105,
    longitude: 19.3065,
  },
  {
    id: "drplFacility_item_275",
    value: "IP81",
    text: "Vällingbybadet",
    latitude: 59.612,
    longitude: 19.312,
  },
  {
    id: "drplFacility_item_276",
    value: "IP82",
    text: "Vällingbyhallen",
    latitude: 59.6135,
    longitude: 19.3175,
  },
  {
    id: "drplFacility_item_277",
    value: "GP82",
    text: "Vällingbyskolan (idrott)",
    latitude: 59.615,
    longitude: 19.323,
  },
  {
    id: "drplFacility_item_278",
    value: "KN73",
    text: "Västberga IP",
    latitude: 59.6165,
    longitude: 19.3285,
  },
  {
    id: "drplFacility_item_279",
    value: "KI13",
    text: "Västboda BP",
    latitude: 59.618,
    longitude: 19.334,
  },
  {
    id: "drplFacility_item_280",
    value: "GM15",
    text: "Västerholms Friskola",
    latitude: 59.6195,
    longitude: 19.3395,
  },
  {
    id: "drplFacility_item_281",
    value: "KL61",
    text: "Västertorps BP",
    latitude: 59.621,
    longitude: 19.345,
  },
  {
    id: "drplFacility_item_282",
    value: "IN31",
    text: "Västertorpsbadet",
    latitude: 59.6225,
    longitude: 19.3505,
  },
  {
    id: "drplFacility_item_283",
    value: "IN32",
    text: "Västertorpshallen",
    latitude: 59.624,
    longitude: 19.356,
  },
  {
    id: "drplFacility_item_284",
    value: "GL61",
    text: "Västertorpsskolan",
    latitude: 59.6255,
    longitude: 19.3615,
  },
  {
    id: "drplFacility_item_285",
    value: "SL61",
    text: "Västertorpsskolan",
    latitude: 59.627,
    longitude: 19.367,
  },
  {
    id: "drplFacility_item_286",
    value: "KD11",
    text: "Zinkensdamms IP",
    latitude: 59.6285,
    longitude: 19.3725,
  },
  {
    id: "drplFacility_item_287",
    value: "KO46",
    text: "Åkeshovs BP",
    latitude: 59.63,
    longitude: 19.378,
  },
  {
    id: "drplFacility_item_288",
    value: "IO41",
    text: "Åkeshovsbadet",
    latitude: 59.6315,
    longitude: 19.3835,
  },
  {
    id: "drplFacility_item_289",
    value: "IO42",
    text: "Åkeshovshallen",
    latitude: 59.633,
    longitude: 19.389,
  },
  {
    id: "drplFacility_item_290",
    value: "IM01",
    text: "Ålgrytes motionsrum",
    latitude: 59.6345,
    longitude: 19.3945,
  },
  {
    id: "drplFacility_item_291",
    value: "GO21",
    text: "Ålstensskolan",
    latitude: 59.636,
    longitude: 19.4,
  },
  {
    id: "drplFacility_item_292",
    value: "GN42",
    text: "Årstadalsskolan",
    latitude: 59.6375,
    longitude: 19.4055,
  },
  {
    id: "drplFacility_item_293",
    value: "KF02",
    text: "Årstagårdens BP",
    latitude: 59.639,
    longitude: 19.411,
  },
  {
    id: "drplFacility_item_294",
    value: "GF01",
    text: "Årstaskolan",
    latitude: 59.6405,
    longitude: 19.4165,
  },
  {
    id: "drplFacility_item_295",
    value: "GD44",
    text: "Åsö Grundskola",
    latitude: 59.642,
    longitude: 19.422,
  },
  {
    id: "drplFacility_item_296",
    value: "SD44",
    text: "Åsö Grundskola skolsalar",
    latitude: 59.6435,
    longitude: 19.4275,
  },
  {
    id: "drplFacility_item_297",
    value: "KL71",
    text: "Älvsjö IP",
    latitude: 59.645,
    longitude: 19.433,
  },
  {
    id: "drplFacility_item_298",
    value: "KO61",
    text: "Ängby IP",
    latitude: 59.6465,
    longitude: 19.4385,
  },
  {
    id: "drplFacility_item_299",
    value: "GO12",
    text: "Äppelviksskolan",
    latitude: 59.648,
    longitude: 19.444,
  },
  {
    id: "drplFacility_item_300",
    value: "KR24",
    text: "Ärvinge BP",
    latitude: 59.6495,
    longitude: 19.4495,
  },
  {
    id: "drplFacility_item_301",
    value: "IR21",
    text: "Ärvingehallen",
    latitude: 59.651,
    longitude: 19.455,
  },
  {
    id: "drplFacility_item_302",
    value: "KK51",
    text: "Örby BP",
    latitude: 59.6525,
    longitude: 19.4605,
  },
  {
    id: "drplFacility_item_303",
    value: "GK51",
    text: "Örbyskolan",
    latitude: 59.654,
    longitude: 19.466,
  },
  {
    id: "drplFacility_item_304",
    value: "GL91",
    text: "Östbergaskolan",
    latitude: 59.6555,
    longitude: 19.4715,
  },
  {
    id: "drplFacility_item_305",
    value: "SL91",
    text: "Östbergaskolan (möte)",
    latitude: 59.657,
    longitude: 19.477,
  },
  {
    id: "drplFacility_item_306",
    value: "KA12",
    text: "Östermalms IP",
    latitude: 59.6585,
    longitude: 19.4825,
  },
  {
    id: "drplFacility_item_307",
    value: "GA32",
    text: "Östermalmsskolan (idrott)",
    latitude: 59.66,
    longitude: 19.488,
  },
  {
    id: "drplFacility_item_308",
    value: "KA75",
    text: "Östra Reals BP",
    latitude: 59.6615,
    longitude: 19.4935,
  },
  {
    id: "drplFacility_item_309",
    value: "GA75",
    text: "Östra Reals Gym (idrott)",
    latitude: 59.663,
    longitude: 19.499,
  },
  {
    id: "drplFacility_item_310",
    value: "SA75",
    text: "Östra Reals Gym (möte)",
    latitude: 59.6645,
    longitude: 19.5045,
  },
];
