// prettier-ignore
const FACILITIES =[
  {id:"drplFacility_item_1", value:"KO43", text:"Abrahamsberg BP"},
  {id:"drplFacility_item_2", value:"GO41", text:"Abrahamsbergssk. (idrott)"},
  {id:"drplFacility_item_3", value:"SO41", text:"Abrahamsbergssk. (möte)"},
  {id:"drplFacility_item_4", value:"GA01", text:"Adolf Fredriks Musikskola"},
  {id:"drplFacility_item_5", value:"GO02", text:"Adolfsbergsskolan"},
  {id:"drplFacility_item_6", value:"GR03", text:"Akalla Grundskola"},
  {id:"drplFacility_item_7", value:"KR01", text:"Akalla Gårds BP"},
  {id:"drplFacility_item_8", value:"GO01", text:"Alviksskolan"},
  {id:"drplFacility_item_9", value:"KN01", text:"Aspuddens IP"},
  {id:"drplFacility_item_10", value:"GN01", text:"Aspuddens Skola"},
  {id:"drplFacility_item_11", value:"KN21", text:"Axelsbergs BP"},
  {id:"drplFacility_item_12", value:"GP33", text:"Backluraskolan"},
  {id:"drplFacility_item_13", value:"KG21", text:"Bagarmossens BP"},
  {id:"drplFacility_item_14", value:"GG21", text:"Bagarmossens Skola"},
  {id:"drplFacility_item_15", value:"KK02", text:"Bandhagens Gymnasium BP"},
  {id:"drplFacility_item_16", value:"GK02", text:"Bandhagens Skola"},
  {id:"drplFacility_item_17", value:"KK03", text:"Bandhagens Skola BP"},
  {id:"drplFacility_item_18", value:"IK01", text:"Bandhagshallen"},
  {id:"drplFacility_item_19", value:"IO82", text:"Beckombergahallen"},
  {id:"drplFacility_item_20", value:"KA15", text:"Bellevue BP"},
  {id:"drplFacility_item_21", value:"KG22", text:"Bergholms BP"},
  {id:"drplFacility_item_22", value:"GG01", text:"Björkhagens Skola (idrott"},
  {id:"drplFacility_item_23", value:"SG01", text:"Björkhagens skola (möte)"},
  {id:"drplFacility_item_24", value:"GP72", text:"Björnbodaskolan"},
  {id:"drplFacility_item_25", value:"KO82", text:"Blackebergs BP"},
  {id:"drplFacility_item_26", value:"IO81", text:"Blackebergshallen"},
  {id:"drplFacility_item_27", value:"GO83", text:"Blackebergsskolan"},
  {id:"drplFacility_item_28", value:"BBLEK", text:"Blekholmsterrassen"},
  {id:"drplFacility_item_29", value:"KM01", text:"Bredängs BP"},
  {id:"drplFacility_item_30", value:"IM03", text:"Bredängsbadet"},
  {id:"drplFacility_item_31", value:"IM02", text:"Bredängshallen"},
  {id:"drplFacility_item_32", value:"GO11", text:"Bromma Gymnasium"},
  {id:"drplFacility_item_33", value:"KO52", text:"Bromma Sportfält"},
  {id:"drplFacility_item_34", value:"KQ51", text:"Bromstens IP"},
  {id:"drplFacility_item_35", value:"GQ51", text:"Bromstensskolan"},
  {id:"drplFacility_item_36", value:"KG23", text:"Brotorps BP"},
  {id:"drplFacility_item_37", value:"KN52", text:"Brännkyrka BP"},
  {id:"drplFacility_item_38", value:"IN51", text:"Brännkyrkahallen"},
  {id:"drplFacility_item_39", value:"KK04", text:"Bäckahagens BP"},
  {id:"drplFacility_item_40", value:"GK21", text:"Bäckahagens Skola"},
  {id:"drplFacility_item_41", value:"KK32", text:"Bäverdalens BP"},
  {id:"drplFacility_item_42", value:"KR13", text:"Dalhagens BP"},
  {id:"drplFacility_item_43", value:"GA83", text:"Eiraskolan"},
  {id:"drplFacility_item_44", value:"GN12", text:"Ekensbergsskolan"},
  {id:"drplFacility_item_45", value:"KA16", text:"Ekhagens BP"},
  {id:"drplFacility_item_46", value:"KQ45", text:"Elinsborgs BP"},
  {id:"drplFacility_item_47", value:"IA12", text:"Engelbrektshallen"},
  {id:"drplFacility_item_48", value:"KF32", text:"Enskede IP"},
  {id:"drplFacility_item_49", value:"GF31", text:"Enskede Skola (idrott)"},
  {id:"drplFacility_item_50", value:"GF21", text:"Enskedefältets Skola"},
  {id:"drplFacility_item_51", value:"IF12", text:"Enskedehallen"},
  {id:"drplFacility_item_52", value:"KD47", text:"Eriksdals BP"},
  {id:"drplFacility_item_53", value:"ID40", text:"Eriksdalsbadet"},
  {id:"drplFacility_item_54", value:"ID42", text:"Eriksdalshallen"},
  {id:"drplFacility_item_55", value:"SD41", text:"Eriksdalsskolan"},
  {id:"drplFacility_item_56", value:"GD41", text:"Eriksdalsskolan (idrott)"},
  {id:"drplFacility_item_57", value:"GA91", text:"Essinge Skola"},
  {id:"drplFacility_item_58", value:"GI01", text:"Fagersjöskolan"},
  {id:"drplFacility_item_59", value:"KI14", text:"Farsta IP"},
  {id:"drplFacility_item_60", value:"II14", text:"Farstahallarna, Farsta IP"},
  {id:"drplFacility_item_61", value:"II15", text:"Farstahallen"},
  {id:"drplFacility_item_62", value:"ID44", text:"Forsgrenska"},
  {id:"drplFacility_item_63", value:"ID43", text:"Forsgrenskabadet"},
  {id:"drplFacility_item_64", value:"KL01", text:"Fruängens BP"},
  {id:"drplFacility_item_65", value:"GL01", text:"Fruängens Skola (idrott)"},
  {id:"drplFacility_item_66", value:"IA11", text:"GIH-badet"},
  {id:"drplFacility_item_67", value:"GD05", text:"Globala gymnasiet"},
  {id:"drplFacility_item_68", value:"KQ20", text:"Gläntans IP"},
  {id:"drplFacility_item_69", value:"KR03", text:"Granby BP"},
  {id:"drplFacility_item_70", value:"KP02", text:"Grimsta BP"},
  {id:"drplFacility_item_71", value:"KP01", text:"Grimsta IP"},
  {id:"drplFacility_item_72", value:"IP01", text:"Grimstahallen"},
  {id:"drplFacility_item_73", value:"KN11", text:"Gröndals BP"},
  {id:"drplFacility_item_74", value:"KH04", text:"Gubbängens BP"},
  {id:"drplFacility_item_75", value:"KH01", text:"Gubbängens IP"},
  {id:"drplFacility_item_76", value:"KH02", text:"Gubbängens Sportfält"},
  {id:"drplFacility_item_77", value:"GH01", text:"Gubbängsbadet"},
  {id:"drplFacility_item_78", value:"KH03", text:"Gubbängsfältet Rugby"},
  {id:"drplFacility_item_79", value:"IH02", text:"Gubbängshallen"},
  {id:"drplFacility_item_80", value:"GH02", text:"Gubbängsskolan (idrott)"},
  {id:"drplFacility_item_81", value:"GQ44", text:"Gullingeskolan"},
  {id:"drplFacility_item_82", value:"GA21", text:"Gustav Vasa Skola (idrott"},
  {id:"drplFacility_item_83", value:"IA31", text:"Gärdeshallen"},
  {id:"drplFacility_item_84", value:"SA71", text:"Gärdesskolan (klassrum)"},
  {id:"drplFacility_item_85", value:"KA31", text:"Gärdesskolans bollplan"},
  {id:"drplFacility_item_86", value:"KA71", text:"Gärdets Sportfält"},
  {id:"drplFacility_item_87", value:"KK12", text:"Hagsätra IP"},
  {id:"drplFacility_item_88", value:"IK25", text:"Hagsätrahallen"},
  {id:"drplFacility_item_89", value:"KD50", text:"Hammarby IP"},
  {id:"drplFacility_item_90", value:"GG03", text:"Hammarby Skola Norra"},
  {id:"drplFacility_item_91", value:"KG01", text:"Hammarbyhöjden IP"},
  {id:"drplFacility_item_92", value:"GG02", text:"Hammarbyskolan Södra"},
  {id:"drplFacility_item_93", value:"KL11", text:"Herrängens BP"},
  {id:"drplFacility_item_94", value:"GL11", text:"Herrängens Skola"},
  {id:"drplFacility_item_95", value:"KA13", text:"Hjorthagens IP"},
  {id:"drplFacility_item_96", value:"IA13", text:"Hjorthagshallen"},
  {id:"drplFacility_item_97", value:"KQ44", text:"Hjulsta BP"},
  {id:"drplFacility_item_98", value:"GQ47", text:"Hjulstaskolan (idrott)"},
  {id:"drplFacility_item_99", value:"KR12", text:"Husby BP"},
  {id:"drplFacility_item_100", value:"KR11", text:"Husby Ishall"},
  {id:"drplFacility_item_101", value:"IR10", text:"Husbybadet"},
  {id:"drplFacility_item_102", value:"SS13", text:"Husbybadet skolsim"},
  {id:"drplFacility_item_103", value:"GR13", text:"Husbygårdsskolan"},
  {id:"drplFacility_item_104", value:"IR11", text:"Husbyhallen"},
  {id:"drplFacility_item_105", value:"GN32", text:"Hägerstenshamnens Skola"},
  {id:"drplFacility_item_106", value:"KN33", text:"Hägerstensåsens BP"},
  {id:"drplFacility_item_107", value:"GN31", text:"Hägerstensåsens Skola"},
  {id:"drplFacility_item_108", value:"KP11", text:"Hässelby Gårds BP"},
  {id:"drplFacility_item_109", value:"KP10", text:"Hässelby IP"},
  {id:"drplFacility_item_110", value:"KP31", text:"Hässelby Villastads BP"},
  {id:"drplFacility_item_111", value:"GP11", text:"Hässelbygårdssk. (idrott)"},
  {id:"drplFacility_item_112", value:"SP11", text:"Hässelbygårdsskolan"},
  {id:"drplFacility_item_113", value:"IP31", text:"Hässelbyhallen"},
  {id:"drplFacility_item_114", value:"KP24", text:"Hässelängens BP"},
  {id:"drplFacility_item_115", value:"KI11", text:"Hästhagens BP"},
  {id:"drplFacility_item_116", value:"GI13", text:"Hästhagsskolan"},
  {id:"drplFacility_item_117", value:"GD01", text:"Högalidsskolan (idrott)"},
  {id:"drplFacility_item_118", value:"KK23", text:"Högdalens BP"},
  {id:"drplFacility_item_119", value:"IK21", text:"Högdalsbadet"},
  {id:"drplFacility_item_120", value:"IK22", text:"Högdalshallen"},
  {id:"drplFacility_item_121", value:"SO23", text:"Höglandsskolan"},
  {id:"drplFacility_item_122", value:"KH12", text:"Hökarängens BP"},
  {id:"drplFacility_item_123", value:"KH14", text:"Hökarängens BP"},
  {id:"drplFacility_item_124", value:"GH11", text:"Hökarängsskolan (idrott)"},
  {id:"drplFacility_item_125", value:"GL31", text:"Johan Skyttesk. (idrott)"},
  {id:"drplFacility_item_126", value:"SL31", text:"Johan Skyttesk. (möte)"},
  {id:"drplFacility_item_127", value:"KA22", text:"Johannes BP"},
  {id:"drplFacility_item_128", value:"GA41", text:"Johannes Skola"},
  {id:"drplFacility_item_129", value:"KM31", text:"Johannesdal BP"},
  {id:"drplFacility_item_130", value:"ID50", text:"Kanalhallen"},
  {id:"drplFacility_item_131", value:"GA24", text:"Karlbergs skola"},
  {id:"drplFacility_item_132", value:"GD42", text:"Katarina Norra Skola"},
  {id:"drplFacility_item_133", value:"KD43", text:"Katarina Södra BP"},
  {id:"drplFacility_item_134", value:"GD43", text:"Katarina Södra Skola"},
  {id:"drplFacility_item_135", value:"GA81", text:"Klastorpsskolan"},
  {id:"drplFacility_item_136", value:"KQ61", text:"Knutby BP"},
  {id:"drplFacility_item_137", value:"GQ30", text:"Knutbyskolan"},
  {id:"drplFacility_item_138", value:"IA82", text:"Konradsbergshallen"},
  {id:"drplFacility_item_139", value:"KA83", text:"Kristinebergs IP"},
  {id:"drplFacility_item_140", value:"GA92", text:"Kristinebergsskolan"},
  {id:"drplFacility_item_141", value:"IA61", text:"Kronobergsbadet"},
  {id:"drplFacility_item_142", value:"GA87", text:"Kungsholmens Grund Nya"},
  {id:"drplFacility_item_143", value:"GA88", text:"Kungsholmens Grundskola"},
  {id:"drplFacility_item_144", value:"GA82", text:"Kungsholmens Gym. (idrott"},
  {id:"drplFacility_item_145", value:"SA82", text:"Kungsholmens Gym. (möte)"},
  {id:"drplFacility_item_146", value:"KA81", text:"Kungsholmens Gymnasium BP"},
  {id:"drplFacility_item_147", value:"KR23", text:"Kvarnbacka BP"},
  {id:"drplFacility_item_148", value:"GR22", text:"Kvarnbackaskolan"},
  {id:"drplFacility_item_149", value:"GQ63", text:"Kvarnbyskolan"},
  {id:"drplFacility_item_150", value:"KI12", text:"Kvickentorps BP"},
  {id:"drplFacility_item_151", value:"KP41", text:"Kälvesta BP"},
  {id:"drplFacility_item_152", value:"KL33", text:"Kämpetorps BP"},
  {id:"drplFacility_item_153", value:"IL33", text:"Kämpetorpshallen"},
  {id:"drplFacility_item_154", value:"KG11", text:"Kärrtorps IP"},
  {id:"drplFacility_item_155", value:"IG11", text:"Kärrtorpshallen"},
  {id:"drplFacility_item_156", value:"IN42", text:"Liljeholmshallen"},
  {id:"drplFacility_item_157", value:"GA02", text:"Lilla Adolf Fredrik Skola"},
  {id:"drplFacility_item_158", value:"GF20", text:"Lindeskolan"},
  {id:"drplFacility_item_159", value:"KL21", text:"Lisebergs BP"},
  {id:"drplFacility_item_160", value:"GP12", text:"Loviselundsskolan"},
  {id:"drplFacility_item_161", value:"KL34", text:"Långbro BP"},
  {id:"drplFacility_item_162", value:"GL32", text:"Långbrodals Gamla Skola"},
  {id:"drplFacility_item_163", value:"KD01", text:"Långholmens BP"},
  {id:"drplFacility_item_164", value:"GI21", text:"Magelungsskolan"},
  {id:"drplFacility_item_165", value:"KP23", text:"Maltesholmsskolans BP"},
  {id:"drplFacility_item_166", value:"GD02", text:"Maria Skola"},
  {id:"drplFacility_item_167", value:"GA61", text:"Matteusskolan (idrott)"},
  {id:"drplFacility_item_168", value:"SA61", text:"Matteusskolan (möte)"},
  {id:"drplFacility_item_169", value:"KQ25", text:"Mellangårdens BP"},
  {id:"drplFacility_item_170", value:"IL02", text:"Mälarhöjden Gymnastikhall"},
  {id:"drplFacility_item_171", value:"KL02", text:"Mälarhöjdens IP"},
  {id:"drplFacility_item_172", value:"GN61", text:"Mälarhöjdens Skola (idr)"},
  {id:"drplFacility_item_173", value:"KO31", text:"Nockebyhovs BP"},
  {id:"drplFacility_item_174", value:"KA43", text:"Norra Reals Bollplan"},
  {id:"drplFacility_item_175", value:"GA43", text:"Norra Reals Gymn (idrott)"},
  {id:"drplFacility_item_176", value:"SA43", text:"Norra Reals Gymn (möte)"},
  {id:"drplFacility_item_177", value:"GO61", text:"Norra Ängby Skola"},
  {id:"drplFacility_item_178", value:"KO44", text:"Nya Element BP"},
  {id:"drplFacility_item_179", value:"GN41", text:"Nybohovsskolan"},
  {id:"drplFacility_item_180", value:"KG03", text:"Nytorps BP"},
  {id:"drplFacility_item_181", value:"KP51", text:"Nälsta BP"},
  {id:"drplFacility_item_182", value:"IP52", text:"Nälstabadet"},
  {id:"drplFacility_item_183", value:"GP51", text:"Nälstaskolan"},
  {id:"drplFacility_item_184", value:"KO32", text:"Olovslunds BP"},
  {id:"drplFacility_item_185", value:"GO32", text:"Olovslundsskolan"},
  {id:"drplFacility_item_186", value:"KK13", text:"Ormkärrs BP"},
  {id:"drplFacility_item_187", value:"GK12", text:"Ormkärrsskolan (idrott)"},
  {id:"drplFacility_item_188", value:"IP32", text:"Riddersvikshallen"},
  {id:"drplFacility_item_189", value:"KQ62", text:"Rinkeby BP"},
  {id:"drplFacility_item_190", value:"IQ62", text:"Rinkebyhallen"},
  {id:"drplFacility_item_191", value:"SQ61", text:"Rinkebyskolan"},
  {id:"drplFacility_item_192", value:"KK31", text:"Rågsveds BP"},
  {id:"drplFacility_item_193", value:"GK31", text:"Rågsvedsskolan"},
  {id:"drplFacility_item_194", value:"GA84", text:"Rålambshovsskolan"},
  {id:"drplFacility_item_195", value:"IA22", text:"Rödabergshallen"},
  {id:"drplFacility_item_196", value:"IA41", text:"S:t Erikshallen"},
  {id:"drplFacility_item_197", value:"KH21", text:"Sandåkra BP"},
  {id:"drplFacility_item_198", value:"GH22", text:"Sandåkraskolan"},
  {id:"drplFacility_item_199", value:"IE51", text:"Sjöstadshallen"},
  {id:"drplFacility_item_200", value:"GE51", text:"Sjöstadsskolan"},
  {id:"drplFacility_item_201", value:"IF01", text:"Sjöviksskolan"},
  {id:"drplFacility_item_202", value:"KL81", text:"Sjöängens BP"},
  {id:"drplFacility_item_203", value:"GL81", text:"Sjöängsskolan"},
  {id:"drplFacility_item_204", value:"IF14", text:"Skanskvarnshallen"},
  {id:"drplFacility_item_205", value:"GF12", text:"Skanskvarnsskolan (idrott"},
  {id:"drplFacility_item_206", value:"ID51", text:"Skanstullshallen"},
  {id:"drplFacility_item_207", value:"GG31", text:"Skarpatorpsskolan F-3"},
  {id:"drplFacility_item_208", value:"KG12", text:"Skarpnäcks BP"},
  {id:"drplFacility_item_209", value:"GG12", text:"Skarpnäcks Skola"},
  {id:"drplFacility_item_210", value:"KG32", text:"Skarpnäcks Sportfält"},
  {id:"drplFacility_item_211", value:"IG32", text:"Skarpnäckshallen"},
  {id:"drplFacility_item_212", value:"SM12", text:"Skärholmens gymnasium"},
  {id:"drplFacility_item_213", value:"IM11", text:"Skärholmsbadet"},
  {id:"drplFacility_item_214", value:"IM12", text:"Skärholmshallen"},
  {id:"drplFacility_item_215", value:"KH22", text:"Sköndals BP"},
  {id:"drplFacility_item_216", value:"IH21", text:"Sköndalshallen"},
  {id:"drplFacility_item_217", value:"GH12", text:"Skönstaholmsskolan"},
  {id:"drplFacility_item_218", value:"GM14", text:"Slättgårdsskolan"},
  {id:"drplFacility_item_219", value:"KP14", text:"Smedshagens BP"},
  {id:"drplFacility_item_220", value:"IP14", text:"Smedshagshallen"},
  {id:"drplFacility_item_221", value:"GO22", text:"Smedslättsskolan"},
  {id:"drplFacility_item_222", value:"GD52", text:"Sofia Skola"},
  {id:"drplFacility_item_223", value:"KD52", text:"Sofiaskolans BP"},
  {id:"drplFacility_item_224", value:"KL51", text:"Solberga BP"},
  {id:"drplFacility_item_225", value:"GL51", text:"Solbergaskolan"},
  {id:"drplFacility_item_226", value:"KQ24", text:"Solhems BP"},
  {id:"drplFacility_item_227", value:"IQ22", text:"Spånga Idrottshall"},
  {id:"drplFacility_item_228", value:"KQ23", text:"Spånga IP"},
  {id:"drplFacility_item_229", value:"IQ21", text:"Spångabadet"},
  {id:"drplFacility_item_230", value:"KA82", text:"Stadshagens IP"},
  {id:"drplFacility_item_231", value:"KR02", text:"Stenhagens BP"},
  {id:"drplFacility_item_232", value:"KH11", text:"Stockholm BMX Arena"},
  {id:"drplFacility_item_233", value:"KA91", text:"Stora Essinge IP"},
  {id:"drplFacility_item_234", value:"IO11", text:"Stora Mossenhallarna idr"},
  {id:"drplFacility_item_235", value:"KO11", text:"Stora Mossens IP"},
  {id:"drplFacility_item_236", value:"GD04", text:"Storkyrkoskolan"},
  {id:"drplFacility_item_237", value:"KK41", text:"Stureby BP"},
  {id:"drplFacility_item_238", value:"GK41", text:"Sturebyskolan"},
  {id:"drplFacility_item_239", value:"KK42", text:"Sturebyskolans BP"},
  {id:"drplFacility_item_240", value:"KQ31", text:"Sundby BP"},
  {id:"drplFacility_item_241", value:"GQ31", text:"Sundbyskolan (gymn)"},
  {id:"drplFacility_item_242", value:"KM22", text:"Sätra BP"},
  {id:"drplFacility_item_243", value:"KM21", text:"Sätra IP"},
  {id:"drplFacility_item_244", value:"KM23", text:"Sätradalens BP"},
  {id:"drplFacility_item_245", value:"IM21", text:"Sätrahallen"},
  {id:"drplFacility_item_246", value:"GM21", text:"Sätraskolan (gymn)"},
  {id:"drplFacility_item_247", value:"GD11", text:"Södermalmsskolan (idrott)"},
  {id:"drplFacility_item_248", value:"SD12", text:"Södra Latins Gymn. (möte)"},
  {id:"drplFacility_item_249", value:"GD12", text:"Södra Latins Gymnasium"},
  {id:"drplFacility_item_250", value:"KO71", text:"Södra Ängby BP"},
  {id:"drplFacility_item_251", value:"GO82", text:"Södra Ängby skola"},
  {id:"drplFacility_item_252", value:"GP41", text:"Sörgårdsskolan"},
  {id:"drplFacility_item_253", value:"KH41", text:"Tallkrogens BP"},
  {id:"drplFacility_item_254", value:"GH41", text:"Tallkrogens Skola"},
  {id:"drplFacility_item_255", value:"KD12", text:"Tantolunden BP"},
  {id:"drplFacility_item_256", value:"IN73", text:"Telefonplanshallen"},
  {id:"drplFacility_item_257", value:"IN52", text:"Tellusborgshallen"},
  {id:"drplFacility_item_258", value:"IQ41", text:"Tenstabadet"},
  {id:"drplFacility_item_259", value:"SS12", text:"Tenstabadet skolsim"},
  {id:"drplFacility_item_260", value:"IQ42", text:"Tenstahallen"},
  {id:"drplFacility_item_261", value:"XA04", text:"Testanläggning PLX"},
  {id:"drplFacility_item_262", value:"XA05", text:"Testanläggning SLX"},
  {id:"drplFacility_item_263", value:"IA81", text:"Thorildshallen"},
  {id:"drplFacility_item_264", value:"KA17", text:"Tillfälliga Haga BP"},
  {id:"drplFacility_item_265", value:"GP32", text:"Trollbodaskolan"},
  {id:"drplFacility_item_266", value:"GD53", text:"Tullgårdsskolan"},
  {id:"drplFacility_item_267", value:"KG33", text:"Tätorps BP"},
  {id:"drplFacility_item_268", value:"GA23", text:"Vasa Real"},
  {id:"drplFacility_item_269", value:"GA22", text:"Vasa Real (Nya)"},
  {id:"drplFacility_item_270", value:"KP71", text:"Vinsta BP"},
  {id:"drplFacility_item_271", value:"GP52", text:"Vinsta grundskola östra"},
  {id:"drplFacility_item_272", value:"IN01", text:"Vintervikshallen"},
  {id:"drplFacility_item_273", value:"KM32", text:"Vårbergs IP"},
  {id:"drplFacility_item_274", value:"KP83", text:"Vällingby BP"},
  {id:"drplFacility_item_275", value:"IP81", text:"Vällingbybadet"},
  {id:"drplFacility_item_276", value:"IP82", text:"Vällingbyhallen"},
  {id:"drplFacility_item_277", value:"GP82", text:"Vällingbyskolan (idrott)"},
  {id:"drplFacility_item_278", value:"KN73", text:"Västberga IP"},
  {id:"drplFacility_item_279", value:"KI13", text:"Västboda BP"},
  {id:"drplFacility_item_280", value:"GM15", text:"Västerholms Friskola"},
  {id:"drplFacility_item_281", value:"KL61", text:"Västertorps BP"},
  {id:"drplFacility_item_282", value:"IN31", text:"Västertorpsbadet"},
  {id:"drplFacility_item_283", value:"IN32", text:"Västertorpshallen"},
  {id:"drplFacility_item_284", value:"GL61", text:"Västertorpsskolan"},
  {id:"drplFacility_item_285", value:"SL61", text:"Västertorpsskolan"},
  {id:"drplFacility_item_286", value:"KD11", text:"Zinkensdamms IP"},
  {id:"drplFacility_item_287", value:"KO46", text:"Åkeshovs BP"},
  {id:"drplFacility_item_288", value:"IO41", text:"Åkeshovsbadet"},
  {id:"drplFacility_item_289", value:"IO42", text:"Åkeshovshallen"},
  {id:"drplFacility_item_290", value:"IM01", text:"Ålgrytes motionsrum"},
  {id:"drplFacility_item_291", value:"GO21", text:"Ålstensskolan"},
  {id:"drplFacility_item_292", value:"GN42", text:"Årstadalsskolan"},
  {id:"drplFacility_item_293", value:"KF02", text:"Årstagårdens BP"},
  {id:"drplFacility_item_294", value:"GF01", text:"Årstaskolan"},
  {id:"drplFacility_item_295", value:"GD44", text:"Åsö Grundskola"},
  {id:"drplFacility_item_296", value:"SD44", text:"Åsö Grundskola skolsalar"},
  {id:"drplFacility_item_297", value:"KL71", text:"Älvsjö IP"},
  {id:"drplFacility_item_298", value:"KO61", text:"Ängby IP"},
  {id:"drplFacility_item_299", value:"GO12", text:"Äppelviksskolan"},
  {id:"drplFacility_item_300", value:"KR24", text:"Ärvinge BP"},
  {id:"drplFacility_item_301", value:"IR21", text:"Ärvingehallen"},
  {id:"drplFacility_item_302", value:"KK51", text:"Örby BP"},
  {id:"drplFacility_item_303", value:"GK51", text:"Örbyskolan"},
  {id:"drplFacility_item_304", value:"GL91", text:"Östbergaskolan"},
  {id:"drplFacility_item_305", value:"SL91", text:"Östbergaskolan (möte)"},
  {id:"drplFacility_item_306", value:"KA12", text:"Östermalms IP"},
  {id:"drplFacility_item_307", value:"GA32", text:"Östermalmsskolan (idrott)"},
  {id:"drplFacility_item_308", value:"KA75", text:"Östra Reals BP"},
  {id:"drplFacility_item_309", value:"GA75", text:"Östra Reals Gym (idrott)"},
  {id:"drplFacility_item_310", value:"SA75", text:"Östra Reals Gym (möte)"},
] as const;
